#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: https://github.com/forcedotcom/wsdl
//!
//! DO NOT EDIT - This file is automatically generated

//! General Mapping Types, Mapping Operations

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
pub enum MappingBehaviorType {
    #[default]
    PointInTime,
    CurrentValue,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
pub enum MappingOperation {
    #[default]
    Autofill,
    Overwrite,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
pub enum MappingUsageType {
    #[default]
    ConvertToSalesAgreement,
    EligibleProgramRebateType,
    MapJournalToMemberAggregate,
    TransformationMapping,
    CLMFieldMapping,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
pub enum MappingType {
    #[default]
    WorkPlans_WorkPlanTemplate_WorkPlan,
    WorkPlans_WorkStepTemplate_WorkStep,
    WorkPlans_WorkPlanTemplateEntry_WorkStep,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
pub enum MappingAlertType {
    #[default]
    None,
    Warning,
    Error,
}

