#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: https://github.com/forcedotcom/wsdl
//!
//! DO NOT EDIT - This file is automatically generated

//! Next Best Action, Recommendations, Strategy Builder

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
pub enum RecommendationChannel {
    #[default]
    DefaultChannel,
    CustomChannel1,
    CustomChannel2,
    CustomChannel3,
    CustomChannel4,
    CustomChannel5,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
pub enum RecommendationConditionOperator {
    #[default]
    EQUALS,
    GREATER_THAN,
    GREATER_THAN_OR_EQUAL_TO,
    LESS_THAN,
    LESS_THAN_OR_EQUAL_TO,
    NOT_EQUALS,
    LIKE,
    STARTS_WITH,
    ENDS_WITH,
    CONTAINS,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
pub enum RecommendationConditionValueType {
    #[default]
    TEXT,
    NUMBER,
    BOOLEAN,
    DATE,
    DATE_TIME,
    TIME,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
pub enum StrategyReactionType {
    #[default]
    Accepted,
    Rejected,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct StrategyNodeInvocableActionArg {
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct StrategyAction {
    #[serde(default)]
    pub action: String,
    #[serde(default)]
    pub argument: Vec<StrategyActionArg>,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub r#type: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct RecommendationDefinition {
    #[serde(rename = "recommendationDefinitionDetails", default)]
    pub recommendation_definition_details: Vec<RecommendationDefinitionDetail>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct RecommendationAudience {
    #[serde(rename = "recommendationAudienceDetails", default)]
    pub recommendation_audience_details: Vec<RecommendationAudienceDetail>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct StrategyActionArg {
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct RecommendationStrategy {
    #[serde(rename = "actionContext", default)]
    pub action_context: Vec<StrategyAction>,
    #[serde(rename = "aiLoad", default)]
    pub ai_load: Vec<serde_json::Value>,
    #[serde(rename = "aiSort", default)]
    pub ai_sort: Vec<serde_json::Value>,
    #[serde(rename = "contextRecordType", default)]
    pub context_record_type: String,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub filter: Vec<serde_json::Value>,
    #[serde(default)]
    pub r#if: Vec<serde_json::Value>,
    #[serde(rename = "invocableAction", default)]
    pub invocable_action: Vec<serde_json::Value>,
    #[serde(rename = "isTemplate", default)]
    pub is_template: bool,
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub map: Vec<serde_json::Value>,
    #[serde(rename = "mutuallyExclusive", default)]
    pub mutually_exclusive: Vec<serde_json::Value>,
    #[serde(rename = "onBehalfOfExpression", default)]
    pub on_behalf_of_expression: String,
    #[serde(rename = "recommendationLimit", default)]
    pub recommendation_limit: Vec<serde_json::Value>,
    #[serde(rename = "recommendationLoad", default)]
    pub recommendation_load: Vec<serde_json::Value>,
    #[serde(default)]
    pub sort: Vec<serde_json::Value>,
    #[serde(default)]
    pub union: Vec<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct StrategyNodeSortField {
    #[serde(default)]
    pub name: String,
    #[serde(rename = "nullsFirst", default)]
    pub nulls_first: bool,
    #[serde(default)]
    pub order: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct RecommendationDefinitionDetail {
    #[serde(rename = "actionUrl", default)]
    pub action_url: String,
    #[serde(default)]
    pub description: String,
    #[serde(rename = "linkText", default)]
    pub link_text: String,
    #[serde(rename = "scheduledRecommendations", default)]
    pub scheduled_recommendations: serde_json::Value,
    #[serde(rename = "setupName", default)]
    pub setup_name: String,
    #[serde(default)]
    pub title: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct RecommendationAudienceDetail {
    #[serde(rename = "audienceCriteriaType", default)]
    pub audience_criteria_type: serde_json::Value,
    #[serde(rename = "audienceCriteriaValue", default)]
    pub audience_criteria_value: String,
    #[serde(rename = "setupName", default)]
    pub setup_name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct RecommendationConditionValue {
    #[serde(default)]
    pub r#type: RecommendationConditionValueType,
    #[serde(default)]
    pub value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct StrategyNodeBase {
    #[serde(rename = "childNode", default)]
    pub child_node: Vec<String>,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct RecommendationLoadCondition {
    #[serde(default)]
    pub field: String,
    #[serde(default)]
    pub operator: RecommendationConditionOperator,
    #[serde(default)]
    pub value: RecommendationConditionValue,
}
