#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: <https://github.com/forcedotcom/wsdl>
//!
//! DO NOT EDIT - This file is automatically generated

//! Apex classes, triggers, and components

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum ApexCodeUnitStatus {
    #[default]
    Inactive,
    Active,
    Deleted,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ApexEmailNotification {
    #[serde(default)]
    pub email: String,
    #[serde(default)]
    pub user: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ApexEmailNotifications {
    #[serde(rename = "apexEmailNotification", default)]
    pub apex_email_notification: Vec<ApexEmailNotification>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ApexTestSuite {
    #[serde(rename = "testClassName", default)]
    pub test_class_name: Vec<String>,
}
