#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: <https://github.com/forcedotcom/wsdl>
//!
//! DO NOT EDIT - This file is automatically generated

//! Batch Jobs, Async Processing, Queues

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum AsyncRequestState {
    #[default]
    Queued,
    InProgress,
    Completed,
    Error,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct AsyncResult {
    #[serde(default)]
    pub done: bool,
    #[serde(default)]
    pub id: serde_json::Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(default)]
    pub state: AsyncRequestState,
    #[serde(
        rename = "statusCode",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub status_code: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct Queue {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(
        rename = "doesSendEmailToMembers",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub does_send_email_to_members: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(default)]
    pub name: String,
    #[serde(
        rename = "queueMembers",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub queue_members: Option<QueueMembers>,
    #[serde(
        rename = "queueRoutingConfig",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub queue_routing_config: Option<String>,
    #[serde(rename = "queueSobject", default)]
    pub queue_sobject: Vec<QueueSobject>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct QueueMembers {
    #[serde(
        rename = "publicGroups",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub public_groups: Option<serde_json::Value>,
    #[serde(
        rename = "roleAndSubordinates",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub role_and_subordinates: Option<serde_json::Value>,
    #[serde(
        rename = "roleAndSubordinatesInternal",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub role_and_subordinates_internal: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub roles: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub users: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct QueueRoutingConfig {
    #[serde(
        rename = "capacityPercentage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub capacity_percentage: Option<f64>,
    #[serde(
        rename = "capacityType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub capacity_type: Option<serde_json::Value>,
    #[serde(
        rename = "capacityWeight",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub capacity_weight: Option<f64>,
    #[serde(
        rename = "dropAdditionalSkillsTimeout",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub drop_additional_skills_timeout: Option<f64>,
    #[serde(
        rename = "isAttributeBased",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_attribute_based: Option<bool>,
    #[serde(default)]
    pub label: String,
    #[serde(
        rename = "pausedCapacityPercentage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub paused_capacity_percentage: Option<f64>,
    #[serde(
        rename = "pausedCapacityWeight",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub paused_capacity_weight: Option<f64>,
    #[serde(
        rename = "pushTimeout",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub push_timeout: Option<f64>,
    #[serde(
        rename = "queueOverflowAssignee",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub queue_overflow_assignee: Option<String>,
    #[serde(rename = "routingModel", default)]
    pub routing_model: serde_json::Value,
    #[serde(rename = "routingPriority", default)]
    pub routing_priority: f64,
    #[serde(default)]
    pub skills: Vec<QueueRoutingConfigSkill>,
    #[serde(
        rename = "userOverflowAssignee",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub user_overflow_assignee: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct QueueRoutingConfigSkill {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub skill: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct QueueSobject {
    #[serde(rename = "sobjectType", default)]
    pub sobject_type: String,
}
