#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: <https://github.com/forcedotcom/wsdl>
//!
//! DO NOT EDIT - This file is automatically generated

//! Einstein Bots and conversational AI

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum BotInvocationMappingType {
    #[default]
    Input,
    Output,
    Error,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum BotNavigationType {
    #[default]
    Call,
    Redirect,
    TransferToAgent,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum BotProvider {
    #[default]
    Custom,
    GoogleCCAI,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum BotQuickReplyType {
    #[default]
    Static,
    Dynamic,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum BotSourceType {
    #[default]
    None,
    B2ASandboxBot,
    B2AProdBot,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum BotStepConditionOperatorType {
    #[default]
    Equals,
    NotEquals,
    IsSet,
    IsNotSet,
    GreaterThan,
    LessThan,
    GreaterThanOrEqualTo,
    LessThanOrEqualTo,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum BotStepType {
    #[default]
    Navigation,
    Invocation,
    VariableOperation,
    Message,
    Wait,
    Group,
    SystemMessage,
    RecordLookup,
    RichMessage,
    GoalStep,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum BotType {
    #[default]
    Bot,
    InternalCopilot,
    ExternalCopilot,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum BotVariableOperationType {
    #[default]
    Set,
    Unset,
    Collect,
    SetConversationLanguage,
    CollectAttachment,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum BotWidgetType {
    #[default]
    Menu,
    Buttons,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct Bot {
    #[serde(
        rename = "agentDSLEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub agent_dsl_enabled: Option<bool>,
    #[serde(
        rename = "agentTemplate",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub agent_template: Option<String>,
    #[serde(rename = "agentType", default, skip_serializing_if = "Option::is_none")]
    pub agent_type: Option<serde_json::Value>,
    #[serde(
        rename = "botMlDomain",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub bot_ml_domain: Option<serde_json::Value>,
    #[serde(rename = "botSource", default, skip_serializing_if = "Option::is_none")]
    pub bot_source: Option<BotSourceType>,
    #[serde(rename = "botUser", default, skip_serializing_if = "Option::is_none")]
    pub bot_user: Option<String>,
    #[serde(rename = "botVersions", default)]
    pub bot_versions: Vec<BotVersion>,
    #[serde(rename = "contextVariables", default)]
    pub context_variables: Vec<serde_json::Value>,
    #[serde(rename = "conversationChannelProviders", default)]
    pub conversation_channel_providers: Vec<serde_json::Value>,
    #[serde(
        rename = "defaultOutboundFlow",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub default_outbound_flow: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(
        rename = "logPrivateConversationData",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub log_private_conversation_data: Option<bool>,
    #[serde(rename = "pageContextVariables", default)]
    pub page_context_variables: Vec<serde_json::Value>,
    #[serde(
        rename = "richContentEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub rich_content_enabled: Option<bool>,
    #[serde(
        rename = "sessionTimeout",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub session_timeout: Option<f64>,
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<BotType>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotBlock {
    #[serde(rename = "botBlockVersions", default)]
    pub bot_block_versions: Vec<BotBlockVersion>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(
        rename = "richContentEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub rich_content_enabled: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotBlockTranslation {
    #[serde(rename = "botBlockVersions", default)]
    pub bot_block_versions: Vec<BotBlockVersionTranslation>,
    #[serde(rename = "fullName", default)]
    pub full_name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotBlockVersion {
    #[serde(rename = "botDialogs", default)]
    pub bot_dialogs: Vec<BotDialog>,
    #[serde(rename = "conversationGoals", default)]
    pub conversation_goals: Vec<serde_json::Value>,
    #[serde(rename = "conversationLanguages", default)]
    pub conversation_languages: String,
    #[serde(rename = "conversationVariables", default)]
    pub conversation_variables: Vec<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "mlDomain", default)]
    pub ml_domain: serde_json::Value,
    #[serde(
        rename = "permissionSet",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub permission_set: Option<String>,
    #[serde(default)]
    pub status: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotBlockVersionTranslation {
    #[serde(rename = "botDialogs", default)]
    pub bot_dialogs: Vec<BotDialogTranslation>,
    #[serde(rename = "fullName", default)]
    pub full_name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotDialog {
    #[serde(
        rename = "botDialogGroup",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub bot_dialog_group: Option<String>,
    #[serde(rename = "botSteps", default)]
    pub bot_steps: Vec<BotStep>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "developerName", default)]
    pub developer_name: String,
    #[serde(
        rename = "isPlaceholderDialog",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_placeholder_dialog: Option<bool>,
    #[serde(default)]
    pub label: String,
    #[serde(rename = "mlIntent", default, skip_serializing_if = "Option::is_none")]
    pub ml_intent: Option<String>,
    #[serde(
        rename = "mlIntentTrainingEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub ml_intent_training_enabled: Option<bool>,
    #[serde(
        rename = "showInFooterMenu",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub show_in_footer_menu: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotDialogGroup {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "developerName", default)]
    pub developer_name: String,
    #[serde(default)]
    pub label: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotDialogTranslation {
    #[serde(rename = "botSteps", default)]
    pub bot_steps: Vec<BotStepTranslation>,
    #[serde(rename = "developerName", default)]
    pub developer_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotInvocation {
    #[serde(
        rename = "invocationActionName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub invocation_action_name: Option<String>,
    #[serde(
        rename = "invocationActionType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub invocation_action_type: Option<serde_json::Value>,
    #[serde(rename = "invocationMappings", default)]
    pub invocation_mappings: Vec<BotInvocationMapping>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotInvocationMapping {
    #[serde(rename = "parameterName", default)]
    pub parameter_name: String,
    #[serde(
        rename = "recordName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub record_name: Option<String>,
    #[serde(rename = "type", default)]
    pub r#type: BotInvocationMappingType,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(
        rename = "variableName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub variable_name: Option<String>,
    #[serde(
        rename = "variableType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub variable_type: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotMessage {
    #[serde(default)]
    pub message: String,
    #[serde(
        rename = "messageIdentifier",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub message_identifier: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotMessageTranslation {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "messageIdentifier", default)]
    pub message_identifier: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotNavigation {
    #[serde(rename = "botNavigationLinks", default)]
    pub bot_navigation_links: Vec<BotNavigationLink>,
    #[serde(rename = "type", default)]
    pub r#type: BotNavigationType,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotNavigationLink {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(
        rename = "targetBotDialog",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub target_bot_dialog: Option<String>,
    #[serde(
        rename = "targetVariable",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub target_variable: Option<String>,
    #[serde(
        rename = "targetVariableType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub target_variable_type: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotQuickReplyOption {
    #[serde(rename = "literalValue", default)]
    pub literal_value: String,
    #[serde(
        rename = "quickReplyOptionIdentifier",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub quick_reply_option_identifier: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotQuickReplyOptionTranslation {
    #[serde(
        rename = "literalValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub literal_value: Option<String>,
    #[serde(rename = "quickReplyOptionIdentifier", default)]
    pub quick_reply_option_identifier: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotStep {
    #[serde(
        rename = "booleanFilter",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub boolean_filter: Option<String>,
    #[serde(
        rename = "botInvocation",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub bot_invocation: Option<BotInvocation>,
    #[serde(rename = "botMessages", default)]
    pub bot_messages: Vec<BotMessage>,
    #[serde(
        rename = "botNavigation",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub bot_navigation: Option<BotNavigation>,
    #[serde(rename = "botStepConditions", default)]
    pub bot_step_conditions: Vec<BotStepCondition>,
    #[serde(rename = "botSteps", default)]
    pub bot_steps: Vec<Box<BotStep>>,
    #[serde(
        rename = "botVariableOperation",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub bot_variable_operation: Option<BotVariableOperation>,
    #[serde(
        rename = "conditionLogicType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub condition_logic_type: Option<serde_json::Value>,
    #[serde(
        rename = "conversationRecordLookup",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub conversation_record_lookup: Option<serde_json::Value>,
    #[serde(rename = "conversationStepGoalMappings", default)]
    pub conversation_step_goal_mappings: Vec<serde_json::Value>,
    #[serde(
        rename = "conversationSystemMessage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub conversation_system_message: Option<serde_json::Value>,
    #[serde(
        rename = "messageDefinition",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub message_definition: Option<serde_json::Value>,
    #[serde(
        rename = "stepIdentifier",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub step_identifier: Option<String>,
    #[serde(rename = "type", default)]
    pub r#type: BotStepType,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotStepCondition {
    #[serde(rename = "leftOperandName", default)]
    pub left_operand_name: String,
    #[serde(rename = "leftOperandType", default)]
    pub left_operand_type: serde_json::Value,
    #[serde(rename = "operatorType", default)]
    pub operator_type: BotStepConditionOperatorType,
    #[serde(
        rename = "rightOperandValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub right_operand_value: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotStepTranslation {
    #[serde(rename = "botMessages", default)]
    pub bot_messages: Vec<BotMessageTranslation>,
    #[serde(rename = "botSteps", default)]
    pub bot_steps: Vec<Box<BotStepTranslation>>,
    #[serde(
        rename = "botVariableOperation",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub bot_variable_operation: Option<BotVariableOperationTranslation>,
    #[serde(rename = "stepIdentifier", default)]
    pub step_identifier: String,
    #[serde(rename = "type", default)]
    pub r#type: BotStepType,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotTemplate {
    #[serde(rename = "agentType", default, skip_serializing_if = "Option::is_none")]
    pub agent_type: Option<serde_json::Value>,
    #[serde(rename = "botDialogGroups", default)]
    pub bot_dialog_groups: Vec<BotDialogGroup>,
    #[serde(rename = "botDialogs", default)]
    pub bot_dialogs: Vec<BotDialog>,
    #[serde(rename = "contextVariables", default)]
    pub context_variables: Vec<serde_json::Value>,
    #[serde(rename = "conversationGoals", default)]
    pub conversation_goals: Vec<serde_json::Value>,
    #[serde(rename = "conversationLanguages", default)]
    pub conversation_languages: String,
    #[serde(rename = "conversationSystemDialogs", default)]
    pub conversation_system_dialogs: Vec<serde_json::Value>,
    #[serde(rename = "conversationVariables", default)]
    pub conversation_variables: Vec<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(
        rename = "entryDialog",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub entry_dialog: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[serde(
        rename = "mainMenuDialog",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub main_menu_dialog: Option<String>,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(rename = "mlDomain", default, skip_serializing_if = "Option::is_none")]
    pub ml_domain: Option<serde_json::Value>,
    #[serde(
        rename = "permissionSet",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub permission_set: Option<String>,
    #[serde(
        rename = "richContentEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub rich_content_enabled: Option<bool>,
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub r#type: Option<BotType>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotTemplateTranslation {
    #[serde(rename = "botDialogs", default)]
    pub bot_dialogs: Vec<BotDialogTranslation>,
    #[serde(rename = "fullName", default)]
    pub full_name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotTranslation {
    #[serde(rename = "botVersions", default)]
    pub bot_versions: Vec<BotVersionTranslation>,
    #[serde(rename = "fullName", default)]
    pub full_name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotVariableOperand {
    #[serde(
        rename = "disableAutoFill",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub disable_auto_fill: Option<bool>,
    #[serde(
        rename = "sourceName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub source_name: Option<String>,
    #[serde(
        rename = "sourceType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub source_type: Option<serde_json::Value>,
    #[serde(
        rename = "sourceValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub source_value: Option<String>,
    #[serde(rename = "targetName", default)]
    pub target_name: String,
    #[serde(rename = "targetType", default)]
    pub target_type: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotVariableOperation {
    #[serde(
        rename = "askCollectIfSet",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub ask_collect_if_set: Option<bool>,
    #[serde(
        rename = "autoSelectIfSingleChoice",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub auto_select_if_single_choice: Option<bool>,
    #[serde(
        rename = "botInvocation",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub bot_invocation: Option<BotInvocation>,
    #[serde(rename = "botMessages", default)]
    pub bot_messages: Vec<BotMessage>,
    #[serde(rename = "botQuickReplyOptions", default)]
    pub bot_quick_reply_options: Vec<BotQuickReplyOption>,
    #[serde(rename = "botVariableOperands", default)]
    pub bot_variable_operands: Vec<BotVariableOperand>,
    #[serde(
        rename = "ignoreIntentRecognition",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub ignore_intent_recognition: Option<bool>,
    #[serde(
        rename = "invalidInputBotNavigation",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub invalid_input_bot_navigation: Option<BotNavigation>,
    #[serde(
        rename = "messageDefinition",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub message_definition: Option<serde_json::Value>,
    #[serde(
        rename = "optionalCollect",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub optional_collect: Option<bool>,
    #[serde(
        rename = "quickReplyOptionTemplate",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub quick_reply_option_template: Option<String>,
    #[serde(
        rename = "quickReplyType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub quick_reply_type: Option<BotQuickReplyType>,
    #[serde(
        rename = "quickReplyWidgetType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub quick_reply_widget_type: Option<BotWidgetType>,
    #[serde(rename = "retryMessages", default)]
    pub retry_messages: Vec<BotMessage>,
    #[serde(
        rename = "sourceVariableName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub source_variable_name: Option<String>,
    #[serde(
        rename = "sourceVariableType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub source_variable_type: Option<serde_json::Value>,
    #[serde(rename = "successMessages", default)]
    pub success_messages: Vec<BotMessage>,
    #[serde(rename = "type", default)]
    pub r#type: BotVariableOperationType,
    #[serde(
        rename = "variableOperationIdentifier",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub variable_operation_identifier: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotVariableOperationTranslation {
    #[serde(rename = "botMessages", default)]
    pub bot_messages: Vec<BotMessageTranslation>,
    #[serde(rename = "botQuickReplyOptions", default)]
    pub bot_quick_reply_options: Vec<BotQuickReplyOptionTranslation>,
    #[serde(
        rename = "quickReplyOptionTemplate",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub quick_reply_option_template: Option<String>,
    #[serde(rename = "retryMessages", default)]
    pub retry_messages: Vec<BotMessageTranslation>,
    #[serde(rename = "successMessages", default)]
    pub success_messages: Vec<BotMessageTranslation>,
    #[serde(rename = "type", default)]
    pub r#type: BotVariableOperationType,
    #[serde(rename = "variableOperationIdentifier", default)]
    pub variable_operation_identifier: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotVersion {
    #[serde(
        rename = "articleAnswersGPTEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub article_answers_gpt_enabled: Option<bool>,
    #[serde(rename = "botDialogGroups", default)]
    pub bot_dialog_groups: Vec<BotDialogGroup>,
    #[serde(rename = "botDialogs", default)]
    pub bot_dialogs: Vec<BotDialog>,
    #[serde(
        rename = "citationsEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub citations_enabled: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub company: Option<String>,
    #[serde(rename = "conversationDefinitionPlanners", default)]
    pub conversation_definition_planners: Vec<serde_json::Value>,
    #[serde(rename = "conversationGoals", default)]
    pub conversation_goals: Vec<serde_json::Value>,
    #[serde(rename = "conversationSystemDialogs", default)]
    pub conversation_system_dialogs: Vec<serde_json::Value>,
    #[serde(rename = "conversationVariables", default)]
    pub conversation_variables: Vec<serde_json::Value>,
    #[serde(
        rename = "copilotPrimaryLanguage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub copilot_primary_language: Option<serde_json::Value>,
    #[serde(
        rename = "copilotSecondaryLanguages",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub copilot_secondary_languages: Option<String>,
    #[serde(
        rename = "defaultStdObjForContactIdFltrEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub default_std_obj_for_contact_id_fltr_enabled: Option<bool>,
    #[serde(rename = "entryDialog", default)]
    pub entry_dialog: String,
    #[serde(
        rename = "initialIntentDetectionEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub initial_intent_detection_enabled: Option<bool>,
    #[serde(
        rename = "intentDisambiguationEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub intent_disambiguation_enabled: Option<bool>,
    #[serde(
        rename = "intentThreshold",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub intent_threshold: Option<f64>,
    #[serde(
        rename = "intentV3Enabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub intent_v_3_enabled: Option<bool>,
    #[serde(
        rename = "isScriptCompatibleAgent",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_script_compatible_agent: Option<bool>,
    #[serde(
        rename = "knowledgeActionEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub knowledge_action_enabled: Option<bool>,
    #[serde(
        rename = "knowledgeFallbackEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub knowledge_fallback_enabled: Option<bool>,
    #[serde(
        rename = "mainMenuDialog",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub main_menu_dialog: Option<String>,
    #[serde(rename = "nlpProviders", default)]
    pub nlp_providers: Vec<serde_json::Value>,
    #[serde(
        rename = "responseDelayMilliseconds",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub response_delay_milliseconds: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    #[serde(
        rename = "smallTalkEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub small_talk_enabled: Option<bool>,
    #[serde(
        rename = "staticPromptsEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub static_prompts_enabled: Option<bool>,
    #[serde(
        rename = "stopRecPrompts",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub stop_rec_prompts: Option<bool>,
    #[serde(
        rename = "stopWelcomePrompts",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub stop_welcome_prompts: Option<bool>,
    #[serde(
        rename = "surfacesEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub surfaces_enabled: Option<bool>,
    #[serde(rename = "toneType", default, skip_serializing_if = "Option::is_none")]
    pub tone_type: Option<serde_json::Value>,
    #[serde(rename = "welcomeRecommendations", default)]
    pub welcome_recommendations: Vec<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BotVersionTranslation {
    #[serde(rename = "botDialogs", default)]
    pub bot_dialogs: Vec<BotDialogTranslation>,
    #[serde(rename = "fullName", default)]
    pub full_name: String,
}
