#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: https://github.com/forcedotcom/wsdl
//!
//! DO NOT EDIT - This file is automatically generated

//! Call Center, CTI, Telephony Integration

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum CalloutStatus {
    #[default]
    Enabled,
    Disabled,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CallCenter {
    #[serde(rename = "adapterUrl", default)]
    pub adapter_url: String,
    #[serde(rename = "contactCenterChannels", default)]
    pub contact_center_channels: Vec<serde_json::Value>,
    #[serde(rename = "customSettings", default)]
    pub custom_settings: String,
    #[serde(rename = "displayName", default)]
    pub display_name: String,
    #[serde(rename = "displayNameLabel", default)]
    pub display_name_label: String,
    #[serde(rename = "internalNameLabel", default)]
    pub internal_name_label: String,
    #[serde(default)]
    pub sections: Vec<CallCenterSection>,
    #[serde(rename = "vendorCallCenterStatusMaps", default)]
    pub vendor_call_center_status_maps: Vec<serde_json::Value>,
    #[serde(default)]
    pub version: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CallCoachingMediaProvider {
    #[serde(rename = "isActive", default)]
    pub is_active: bool,
    #[serde(rename = "providerDescription", default)]
    pub provider_description: String,
    #[serde(rename = "providerName", default)]
    pub provider_name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CallCtrAgentFavTrfrDest {
    #[serde(default)]
    pub agent: String,
    #[serde(rename = "callCenter", default)]
    pub call_center: String,
    #[serde(default)]
    pub name: String,
    #[serde(rename = "transferDestination", default)]
    pub transfer_destination: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CallCenterItem {
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CallCenterSection {
    #[serde(default)]
    pub items: Vec<CallCenterItem>,
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CallCenterRoutingMap {
    #[serde(rename = "callCenter", default)]
    pub call_center: String,
    #[serde(rename = "developerName", default)]
    pub developer_name: String,
    #[serde(rename = "externalId", default)]
    pub external_id: String,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(rename = "quickConnect", default)]
    pub quick_connect: String,
    #[serde(rename = "referenceRecord", default)]
    pub reference_record: String,
}
