#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: https://github.com/forcedotcom/wsdl
//!
//! DO NOT EDIT - This file is automatically generated

//! Channel Definitions, Channel Layouts

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum Channel {
    #[default]
    AllChannels,
    App,
    Pkb,
    Csp,
    Prm,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum ChannelMode {
    #[default]
    Messaging,
    Voice,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum ChannelSource {
    #[default]
    Other,
    Phone,
    Chat,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum ChannelType {
    #[default]
    FacebookMessenger,
    Text,
    WeChat,
    WhatsApp,
    Phone,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ChannelLayout {
    #[serde(rename = "doesExcludeFieldLabels", default)]
    pub does_exclude_field_labels: bool,
    #[serde(rename = "doesExcludeFiles", default)]
    pub does_exclude_files: bool,
    #[serde(rename = "enabledChannels", default)]
    pub enabled_channels: Vec<String>,
    #[serde(default)]
    pub label: String,
    #[serde(rename = "layoutItems", default)]
    pub layout_items: Vec<ChannelLayoutItem>,
    #[serde(rename = "recordType", default)]
    pub record_type: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ChannelLayoutItem {
    #[serde(default)]
    pub field: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ChannelObjectLinkingRule {
    #[serde(rename = "actionForNoRecordFound", default)]
    pub action_for_no_record_found: serde_json::Value,
    #[serde(rename = "actionForSingleRecordFound", default)]
    pub action_for_single_record_found: serde_json::Value,
    #[serde(rename = "channelType", default)]
    pub channel_type: ChannelType,
    #[serde(default)]
    pub description: String,
    #[serde(rename = "isLinkedRecordOpenedAsSubTab", default)]
    pub is_linked_record_opened_as_sub_tab: bool,
    #[serde(rename = "isRuleActive", default)]
    pub is_rule_active: bool,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(rename = "objectToLink", default)]
    pub object_to_link: serde_json::Value,
    #[serde(rename = "ruleName", default)]
    pub rule_name: String,
}

