#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: <https://github.com/forcedotcom/wsdl>
//!
//! DO NOT EDIT - This file is automatically generated

//! Commerce Cloud, Web Stores, Products, Pricing

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum OrderLifeCycleType {
    #[default]
    MANAGED,
    UNMANAGED,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum ProductGrouping {
    #[default]
    BestMatch,
    VariationParent,
    NoGrouping,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum WebStoreType {
    #[default]
    B2B,
    B2C,
    B2CE,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PaymentGatewayProvider {
    #[serde(
        rename = "apexAdapter",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub apex_adapter: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comments: Option<String>,
    #[serde(
        rename = "gatewayType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub gateway_type: Option<serde_json::Value>,
    #[serde(rename = "idempotencySupported", default)]
    pub idempotency_supported: serde_json::Value,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProductAttrDisplayConfig {
    #[serde(rename = "dataType", default)]
    pub data_type: String,
    #[serde(rename = "displayType", default)]
    pub display_type: String,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(default)]
    pub status: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProductAttributeSet {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "developerName", default)]
    pub developer_name: String,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(rename = "productAttributeSetItems", default)]
    pub product_attribute_set_items: Vec<ProductAttributeSetItem>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProductAttributeSetItem {
    #[serde(default)]
    pub field: String,
    #[serde(
        rename = "isGroupedBy",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_grouped_by: Option<bool>,
    #[serde(default)]
    pub sequence: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProductSpecificationRecType {
    #[serde(rename = "isCommercial", default)]
    pub is_commercial: bool,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(rename = "productSpecificationType", default)]
    pub product_specification_type: String,
    #[serde(rename = "recordType", default)]
    pub record_type: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProductSpecificationType {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProductSpecificationTypeTranslation {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct WebStoreBundle {
    #[serde(
        rename = "autoFacetingEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub auto_faceting_enabled: Option<bool>,
    #[serde(
        rename = "cartToOrderAutoCustomFieldMapping",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub cart_to_order_auto_custom_field_mapping: Option<bool>,
    #[serde(
        rename = "commerceEinsteinActivitiesTracked",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub commerce_einstein_activities_tracked: Option<bool>,
    #[serde(
        rename = "commerceEinsteinDeployed",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub commerce_einstein_deployed: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub country: Option<serde_json::Value>,
    #[serde(
        rename = "defaultCurrency",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub default_currency: Option<String>,
    #[serde(
        rename = "defaultLanguage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub default_language: Option<String>,
    #[serde(rename = "defaultTaxLocaleType", default)]
    pub default_tax_locale_type: serde_json::Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(
        rename = "guestBrowsingEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub guest_browsing_enabled: Option<bool>,
    #[serde(
        rename = "guestCartTimeToLive",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub guest_cart_time_to_live: Option<f64>,
    #[serde(default)]
    pub label: String,
    #[serde(
        rename = "orderLifeCycleType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub order_life_cycle_type: Option<OrderLifeCycleType>,
    #[serde(rename = "pricingStrategy", default)]
    pub pricing_strategy: serde_json::Value,
    #[serde(
        rename = "productGrouping",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub product_grouping: Option<ProductGrouping>,
    #[serde(
        rename = "skipAdditionalEntitlementCheckForSearch",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub skip_additional_entitlement_check_for_search: Option<bool>,
    #[serde(
        rename = "skuDetectionEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub sku_detection_enabled: Option<bool>,
    #[serde(rename = "storeName", default, skip_serializing_if = "Option::is_none")]
    pub store_name: Option<String>,
    #[serde(
        rename = "supportedCurrencies",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub supported_currencies: Option<String>,
    #[serde(
        rename = "supportedLanguages",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub supported_languages: Option<String>,
    #[serde(
        rename = "supportedShipToCountries",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub supported_ship_to_countries: Option<String>,
    #[serde(rename = "type", default)]
    pub r#type: WebStoreType,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct WebStoreTemplate {
    #[serde(
        rename = "autoFacetingEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub auto_faceting_enabled: Option<bool>,
    #[serde(
        rename = "cartAsyncProcessingEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub cart_async_processing_enabled: Option<bool>,
    #[serde(
        rename = "cartCalculateEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub cart_calculate_enabled: Option<bool>,
    #[serde(
        rename = "cartToOrderAutoCustomFieldMapping",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub cart_to_order_auto_custom_field_mapping: Option<bool>,
    #[serde(
        rename = "checkoutTimeToLive",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub checkout_time_to_live: Option<f64>,
    #[serde(
        rename = "checkoutValidAfterDate",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub checkout_valid_after_date: Option<serde_json::Value>,
    #[serde(
        rename = "commerceEinsteinActivitiesTracked",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub commerce_einstein_activities_tracked: Option<bool>,
    #[serde(
        rename = "commerceEinsteinDeployed",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub commerce_einstein_deployed: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub country: Option<serde_json::Value>,
    #[serde(
        rename = "defaultCurrency",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub default_currency: Option<String>,
    #[serde(rename = "defaultLanguage", default)]
    pub default_language: String,
    #[serde(rename = "defaultTaxLocaleType", default)]
    pub default_tax_locale_type: serde_json::Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(
        rename = "duplicateCartItemsEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub duplicate_cart_items_enabled: Option<bool>,
    #[serde(
        rename = "guestBrowsingEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub guest_browsing_enabled: Option<bool>,
    #[serde(rename = "guestCartEnabled", default)]
    pub guest_cart_enabled: bool,
    #[serde(
        rename = "guestCartTimeToLive",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub guest_cart_time_to_live: Option<f64>,
    #[serde(rename = "guestCheckoutEnabled", default)]
    pub guest_checkout_enabled: bool,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(
        rename = "maxValuesPerFacet",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_values_per_facet: Option<f64>,
    #[serde(
        rename = "orderActivationStatus",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub order_activation_status: Option<String>,
    #[serde(
        rename = "orderLifeCycleType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub order_life_cycle_type: Option<OrderLifeCycleType>,
    #[serde(
        rename = "paginationSize",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pagination_size: Option<f64>,
    #[serde(rename = "preserveGuestCartEnabled", default)]
    pub preserve_guest_cart_enabled: bool,
    #[serde(rename = "pricingStrategy", default)]
    pub pricing_strategy: serde_json::Value,
    #[serde(
        rename = "productGrouping",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub product_grouping: Option<ProductGrouping>,
    #[serde(
        rename = "skipAdditionalEntitlementCheckForSearch",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub skip_additional_entitlement_check_for_search: Option<bool>,
    #[serde(
        rename = "skuDetectionEnabled",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub sku_detection_enabled: Option<bool>,
    #[serde(rename = "splitShipmentEnabled", default)]
    pub split_shipment_enabled: bool,
    #[serde(
        rename = "supportedCurrencies",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub supported_currencies: Option<String>,
    #[serde(rename = "supportedLanguages", default)]
    pub supported_languages: String,
    #[serde(
        rename = "supportedShipToCountries",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub supported_ship_to_countries: Option<String>,
    #[serde(rename = "type", default)]
    pub r#type: WebStoreType,
}
