#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: <https://github.com/forcedotcom/wsdl>
//!
//! DO NOT EDIT - This file is automatically generated

//! Custom Metadata, Custom Labels, Custom Tabs

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum CustomChannelConnectedAppType {
    #[default]
    Partner,
    Customer,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum CustomSettingsType {
    #[default]
    List,
    Hierarchy,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CustomApplicationComponent {
    #[serde(
        rename = "buttonIconUrl",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub button_icon_url: Option<String>,
    #[serde(
        rename = "buttonStyle",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub button_style: Option<String>,
    #[serde(
        rename = "buttonText",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub button_text: Option<String>,
    #[serde(
        rename = "buttonWidth",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub button_width: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub height: Option<f64>,
    #[serde(rename = "isHeightFixed", default)]
    pub is_height_fixed: bool,
    #[serde(rename = "isHidden", default)]
    pub is_hidden: bool,
    #[serde(rename = "isWidthFixed", default)]
    pub is_width_fixed: bool,
    #[serde(rename = "visualforcePage", default)]
    pub visualforce_page: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub width: Option<f64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CustomConsoleComponents {
    #[serde(
        rename = "primaryTabComponents",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub primary_tab_components: Option<serde_json::Value>,
    #[serde(
        rename = "subtabComponents",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub subtab_components: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CustomHelpMenuSection {
    #[serde(rename = "customHelpMenuItems", default)]
    pub custom_help_menu_items: Vec<serde_json::Value>,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CustomHttpHeader {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "headerFieldName", default)]
    pub header_field_name: String,
    #[serde(rename = "headerFieldValue", default)]
    pub header_field_value: String,
    #[serde(rename = "isActive", default, skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CustomLabel {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub categories: Option<String>,
    #[serde(default)]
    pub language: String,
    #[serde(default)]
    pub protected: bool,
    #[serde(rename = "shortDescription", default)]
    pub short_description: String,
    #[serde(default)]
    pub value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CustomLabelTranslation {
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CustomLabels {
    #[serde(default)]
    pub labels: Vec<CustomLabel>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CustomMetadata {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub protected: Option<bool>,
    #[serde(default)]
    pub values: Vec<CustomMetadataValue>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CustomMetadataValue {
    #[serde(default)]
    pub field: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CustomNotificationActionDefinition {
    #[serde(rename = "actionLabel", default)]
    pub action_label: String,
    #[serde(rename = "actionName", default)]
    pub action_name: String,
    #[serde(
        rename = "actionTarget",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub action_target: Option<String>,
    #[serde(rename = "actionType", default)]
    pub action_type: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CustomNotificationActionGroup {
    #[serde(default)]
    pub actions: Vec<CustomNotificationActionDefinition>,
    #[serde(rename = "groupName", default)]
    pub group_name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CustomNotificationType {
    #[serde(rename = "actionGroups", default)]
    pub action_groups: Vec<CustomNotificationActionGroup>,
    #[serde(rename = "customNotifTypeName", default)]
    pub custom_notif_type_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default)]
    pub desktop: bool,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(default)]
    pub mobile: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub slack: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CustomPageWebLink {
    #[serde(default)]
    pub availability: serde_json::Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "displayType", default)]
    pub display_type: serde_json::Value,
    #[serde(
        rename = "encodingKey",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub encoding_key: Option<serde_json::Value>,
    #[serde(
        rename = "hasMenubar",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub has_menubar: Option<bool>,
    #[serde(
        rename = "hasScrollbars",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub has_scrollbars: Option<bool>,
    #[serde(
        rename = "hasToolbar",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub has_toolbar: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub height: Option<f64>,
    #[serde(
        rename = "isResizable",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_resizable: Option<bool>,
    #[serde(rename = "linkType", default)]
    pub link_type: serde_json::Value,
    #[serde(
        rename = "masterLabel",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub master_label: Option<String>,
    #[serde(rename = "openType", default)]
    pub open_type: serde_json::Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub page: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub position: Option<serde_json::Value>,
    #[serde(default)]
    pub protected: bool,
    #[serde(
        rename = "requireRowSelection",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub require_row_selection: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scontrol: Option<String>,
    #[serde(
        rename = "showsLocation",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub shows_location: Option<bool>,
    #[serde(
        rename = "showsStatus",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub shows_status: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub width: Option<f64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CustomPageWebLinkTranslation {
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CustomPermission {
    #[serde(
        rename = "connectedApp",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub connected_app: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(
        rename = "externalClientApplication",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub external_client_application: Option<String>,
    #[serde(rename = "isLicensed", default)]
    pub is_licensed: bool,
    #[serde(default)]
    pub label: String,
    #[serde(rename = "requiredPermission", default)]
    pub required_permission: Vec<CustomPermissionDependencyRequired>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CustomPermissionDependencyRequired {
    #[serde(rename = "customPermission", default)]
    pub custom_permission: String,
    #[serde(default)]
    pub dependency: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CustomTab {
    #[serde(rename = "actionOverrides", default)]
    pub action_overrides: Vec<serde_json::Value>,
    #[serde(
        rename = "auraComponent",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub aura_component: Option<String>,
    #[serde(
        rename = "customObject",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub custom_object: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "flexiPage", default, skip_serializing_if = "Option::is_none")]
    pub flexi_page: Option<String>,
    #[serde(
        rename = "frameHeight",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub frame_height: Option<f64>,
    #[serde(
        rename = "hasSidebar",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub has_sidebar: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(
        rename = "lwcComponent",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub lwc_component: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub motif: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub page: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scontrol: Option<String>,
    #[serde(
        rename = "splashPageLink",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub splash_page_link: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(
        rename = "urlEncodingKey",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub url_encoding_key: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CustomTabTranslation {
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub name: String,
}
