#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: https://github.com/forcedotcom/wsdl
//!
//! DO NOT EDIT - This file is automatically generated

//! Deploy Options, Deploy Details, Deploy Problems

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DeployProblemType {
    #[default]
    Warning,
    Error,
    Info,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DeployResult {
    #[serde(rename = "canceledBy", default)]
    pub canceled_by: String,
    #[serde(rename = "canceledByName", default)]
    pub canceled_by_name: String,
    #[serde(rename = "checkOnly", default)]
    pub check_only: bool,
    #[serde(rename = "completedDate", default)]
    pub completed_date: String,
    #[serde(rename = "createdBy", default)]
    pub created_by: String,
    #[serde(rename = "createdByName", default)]
    pub created_by_name: String,
    #[serde(rename = "createdDate", default)]
    pub created_date: String,
    #[serde(default)]
    pub details: DeployDetails,
    #[serde(default)]
    pub done: bool,
    #[serde(rename = "errorMessage", default)]
    pub error_message: String,
    #[serde(rename = "errorStatusCode", default)]
    pub error_status_code: serde_json::Value,
    #[serde(default)]
    pub id: serde_json::Value,
    #[serde(rename = "ignoreWarnings", default)]
    pub ignore_warnings: bool,
    #[serde(rename = "lastModifiedDate", default)]
    pub last_modified_date: String,
    #[serde(rename = "numberComponentErrors", default)]
    pub number_component_errors: f64,
    #[serde(rename = "numberComponentsDeployed", default)]
    pub number_components_deployed: f64,
    #[serde(rename = "numberComponentsTotal", default)]
    pub number_components_total: f64,
    #[serde(rename = "numberFiles", default)]
    pub number_files: f64,
    #[serde(rename = "numberTestErrors", default)]
    pub number_test_errors: f64,
    #[serde(rename = "numberTestsCompleted", default)]
    pub number_tests_completed: f64,
    #[serde(rename = "numberTestsTotal", default)]
    pub number_tests_total: f64,
    #[serde(rename = "rollbackOnError", default)]
    pub rollback_on_error: bool,
    #[serde(rename = "runTestsEnabled", default)]
    pub run_tests_enabled: bool,
    #[serde(rename = "startDate", default)]
    pub start_date: String,
    #[serde(rename = "stateDetail", default)]
    pub state_detail: String,
    #[serde(default)]
    pub status: serde_json::Value,
    #[serde(default)]
    pub success: bool,
    #[serde(rename = "zipSize", default)]
    pub zip_size: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DeployOptions {
    #[serde(rename = "allowMissingFiles", default)]
    pub allow_missing_files: bool,
    #[serde(rename = "autoUpdatePackage", default)]
    pub auto_update_package: bool,
    #[serde(rename = "checkOnly", default)]
    pub check_only: bool,
    #[serde(rename = "ignoreWarnings", default)]
    pub ignore_warnings: bool,
    #[serde(rename = "performRetrieve", default)]
    pub perform_retrieve: bool,
    #[serde(rename = "purgeOnDelete", default)]
    pub purge_on_delete: bool,
    #[serde(rename = "rollbackOnError", default)]
    pub rollback_on_error: bool,
    #[serde(rename = "runTests", default)]
    pub run_tests: Vec<String>,
    #[serde(rename = "singlePackage", default)]
    pub single_package: bool,
    #[serde(rename = "testLevel", default)]
    pub test_level: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DeployMessage {
    #[serde(default)]
    pub changed: bool,
    #[serde(rename = "columnNumber", default)]
    pub column_number: f64,
    #[serde(rename = "componentType", default)]
    pub component_type: String,
    #[serde(default)]
    pub created: bool,
    #[serde(rename = "createdDate", default)]
    pub created_date: String,
    #[serde(default)]
    pub deleted: bool,
    #[serde(rename = "fileName", default)]
    pub file_name: String,
    #[serde(rename = "fullName", default)]
    pub full_name: String,
    #[serde(default)]
    pub id: String,
    #[serde(rename = "lineNumber", default)]
    pub line_number: f64,
    #[serde(default)]
    pub problem: String,
    #[serde(rename = "problemType", default)]
    pub problem_type: DeployProblemType,
    #[serde(default)]
    pub success: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DeployDetails {
    #[serde(rename = "componentFailures", default)]
    pub component_failures: Vec<DeployMessage>,
    #[serde(rename = "componentSuccesses", default)]
    pub component_successes: Vec<DeployMessage>,
    #[serde(rename = "retrieveResult", default)]
    pub retrieve_result: serde_json::Value,
    #[serde(rename = "runTestResult", default)]
    pub run_test_result: serde_json::Value,
}
