#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: <https://github.com/forcedotcom/wsdl>
//!
//! DO NOT EDIT - This file is automatically generated

//! Deploy Options, Deploy Details, Deploy Problems

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DeployProblemType {
    #[default]
    Warning,
    Error,
    Info,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DeployDetails {
    #[serde(rename = "componentFailures", default)]
    pub component_failures: Vec<DeployMessage>,
    #[serde(rename = "componentSuccesses", default)]
    pub component_successes: Vec<DeployMessage>,
    #[serde(
        rename = "retrieveResult",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub retrieve_result: Option<serde_json::Value>,
    #[serde(
        rename = "runTestResult",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub run_test_result: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DeployMessage {
    #[serde(default)]
    pub changed: bool,
    #[serde(
        rename = "columnNumber",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub column_number: Option<f64>,
    #[serde(
        rename = "componentType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub component_type: Option<String>,
    #[serde(default)]
    pub created: bool,
    #[serde(rename = "createdDate", default)]
    pub created_date: serde_json::Value,
    #[serde(default)]
    pub deleted: bool,
    #[serde(rename = "fileName", default)]
    pub file_name: String,
    #[serde(rename = "fullName", default)]
    pub full_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(
        rename = "lineNumber",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub line_number: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub problem: Option<String>,
    #[serde(
        rename = "problemType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub problem_type: Option<DeployProblemType>,
    #[serde(default)]
    pub success: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DeployOptions {
    #[serde(rename = "allowMissingFiles", default)]
    pub allow_missing_files: bool,
    #[serde(rename = "autoUpdatePackage", default)]
    pub auto_update_package: bool,
    #[serde(rename = "checkOnly", default)]
    pub check_only: bool,
    #[serde(rename = "ignoreWarnings", default)]
    pub ignore_warnings: bool,
    #[serde(rename = "performRetrieve", default)]
    pub perform_retrieve: bool,
    #[serde(rename = "purgeOnDelete", default)]
    pub purge_on_delete: bool,
    #[serde(rename = "rollbackOnError", default)]
    pub rollback_on_error: bool,
    #[serde(rename = "runTests", default)]
    pub run_tests: Vec<String>,
    #[serde(rename = "singlePackage", default)]
    pub single_package: bool,
    #[serde(rename = "testLevel", default)]
    pub test_level: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DeployResult {
    #[serde(
        rename = "canceledBy",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub canceled_by: Option<String>,
    #[serde(
        rename = "canceledByName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub canceled_by_name: Option<String>,
    #[serde(rename = "checkOnly", default)]
    pub check_only: bool,
    #[serde(
        rename = "completedDate",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub completed_date: Option<serde_json::Value>,
    #[serde(rename = "createdBy", default)]
    pub created_by: String,
    #[serde(rename = "createdByName", default)]
    pub created_by_name: String,
    #[serde(rename = "createdDate", default)]
    pub created_date: serde_json::Value,
    #[serde(default)]
    pub details: DeployDetails,
    #[serde(default)]
    pub done: bool,
    #[serde(
        rename = "errorMessage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub error_message: Option<String>,
    #[serde(
        rename = "errorStatusCode",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub error_status_code: Option<serde_json::Value>,
    #[serde(default)]
    pub id: serde_json::Value,
    #[serde(rename = "ignoreWarnings", default)]
    pub ignore_warnings: bool,
    #[serde(
        rename = "lastModifiedDate",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub last_modified_date: Option<serde_json::Value>,
    #[serde(rename = "numberComponentErrors", default)]
    pub number_component_errors: f64,
    #[serde(rename = "numberComponentsDeployed", default)]
    pub number_components_deployed: f64,
    #[serde(rename = "numberComponentsTotal", default)]
    pub number_components_total: f64,
    #[serde(
        rename = "numberFiles",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub number_files: Option<f64>,
    #[serde(rename = "numberTestErrors", default)]
    pub number_test_errors: f64,
    #[serde(rename = "numberTestsCompleted", default)]
    pub number_tests_completed: f64,
    #[serde(rename = "numberTestsTotal", default)]
    pub number_tests_total: f64,
    #[serde(rename = "rollbackOnError", default)]
    pub rollback_on_error: bool,
    #[serde(rename = "runTestsEnabled", default)]
    pub run_tests_enabled: bool,
    #[serde(rename = "startDate", default, skip_serializing_if = "Option::is_none")]
    pub start_date: Option<serde_json::Value>,
    #[serde(
        rename = "stateDetail",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub state_detail: Option<String>,
    #[serde(default)]
    pub status: serde_json::Value,
    #[serde(default)]
    pub success: bool,
    #[serde(rename = "zipSize", default, skip_serializing_if = "Option::is_none")]
    pub zip_size: Option<f64>,
}
