#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: https://github.com/forcedotcom/wsdl
//!
//! DO NOT EDIT - This file is automatically generated

//! Einstein Discovery, Predictive Analytics

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DiscoveryAIModelStatus {
    #[default]
    Disabled,
    Uploading,
    UploadFailed,
    UploadCompleted,
    Validating,
    ValidationFailed,
    ValidationCompleted,
    Enabled,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DiscoveryAIModelTransformationType {
    #[default]
    TypographicClustering,
    SentimentAnalysis,
    FreeTextClustering,
    NumericalImputation,
    CategoricalImputation,
    TimeSeriesForecast,
    ExtractMonthOfYear,
    ExtractDayOfWeek,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DiscoveryAlgorithmType {
    #[default]
    Glm,
    Gbm,
    Xgboost,
    Drf,
    Best,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DiscoveryFieldMapSourceType {
    #[default]
    SalesforceField,
    AnalyticsDatasetField,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DiscoveryFilterFieldType {
    #[default]
    Text,
    Number,
    Date,
    DateTime,
    Boolean,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DiscoveryFilterOperator {
    #[default]
    Equal,
    NotEqual,
    GreaterThan,
    GreaterThanOrEqual,
    LessThan,
    LessThanOrEqual,
    Between,
    NotBetween,
    InSet,
    NotIn,
    Contains,
    StartsWith,
    EndsWith,
    IsNull,
    IsNotNull,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DiscoveryFilterValueType {
    #[default]
    Constant,
    PlaceHolder,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DiscoveryModelFieldType {
    #[default]
    Text,
    Number,
    Date,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DiscoveryModelRuntimeType {
    #[default]
    Discovery,
    H2O,
    Py36Tensorflow244,
    Py37Tensorflow270,
    Py37Scikitlearn102,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DiscoveryModelSourceType {
    #[default]
    Discovery,
    UserUpload,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DiscoveryOutcomeGoal {
    #[default]
    Minimize,
    Maximize,
    None,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DiscoveryPredictionType {
    #[default]
    Unknown,
    Regression,
    Classification,
    MulticlassClassification,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DiscoveryPushbackType {
    #[default]
    AiRecordInsight,
    Direct,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DiscoveryStoryAutopilotStatus {
    #[default]
    Enabled,
    Disabled,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DiscoveryStoryOutcomeGoal {
    #[default]
    Minimize,
    Maximize,
    None,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DiscoveryStoryOutcomeType {
    #[default]
    Count,
    Text,
    Categorical,
    Number,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DiscoveryStorySourceType {
    #[default]
    AnalyticsDataset,
    Report,
    LiveDataset,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DiscoveryCustomPrescribableFieldDefinition {
    #[serde(default)]
    pub filters: Vec<DiscoveryFilter>,
    #[serde(default)]
    pub template: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DiscoveryDeployedModel {
    #[serde(default)]
    pub active: bool,
    #[serde(rename = "aiModel", default)]
    pub ai_model: String,
    #[serde(rename = "classificationThreshold", default)]
    pub classification_threshold: f64,
    #[serde(rename = "fieldMappings", default)]
    pub field_mappings: Vec<DiscoveryFieldMap>,
    #[serde(default)]
    pub filters: Vec<DiscoveryFilter>,
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub name: String,
    #[serde(rename = "prescribableFields", default)]
    pub prescribable_fields: Vec<DiscoveryPrescribableField>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DiscoveryFieldMap {
    #[serde(rename = "mappedField", default)]
    pub mapped_field: String,
    #[serde(rename = "modelField", default)]
    pub model_field: String,
    #[serde(rename = "sobjectFieldJoinKey", default)]
    pub sobject_field_join_key: String,
    #[serde(default)]
    pub source: String,
    #[serde(rename = "sourceFieldJoinKey", default)]
    pub source_field_join_key: String,
    #[serde(rename = "sourceType", default)]
    pub source_type: DiscoveryFieldMapSourceType,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DiscoveryFilter {
    #[serde(default)]
    pub field: String,
    #[serde(default)]
    pub operator: DiscoveryFilterOperator,
    #[serde(default)]
    pub r#type: DiscoveryFilterFieldType,
    #[serde(default)]
    pub values: Vec<DiscoveryFilterValue>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DiscoveryFilterValue {
    #[serde(default)]
    pub r#type: DiscoveryFilterValueType,
    #[serde(default)]
    pub value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DiscoveryGoal {
    #[serde(default)]
    pub active: bool,
    #[serde(rename = "deployedModels", default)]
    pub deployed_models: Vec<DiscoveryDeployedModel>,
    #[serde(default)]
    pub label: String,
    #[serde(rename = "modelCards", default)]
    pub model_cards: Vec<DiscoveryModelCard>,
    #[serde(default)]
    pub outcome: DiscoveryGoalOutcome,
    #[serde(rename = "predictionType", default)]
    pub prediction_type: DiscoveryPredictionType,
    #[serde(rename = "pushbackField", default)]
    pub pushback_field: String,
    #[serde(rename = "pushbackType", default)]
    pub pushback_type: DiscoveryPushbackType,
    #[serde(rename = "subscribedEntity", default)]
    pub subscribed_entity: String,
    #[serde(rename = "terminalStateFilters", default)]
    pub terminal_state_filters: Vec<DiscoveryFilter>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DiscoveryGoalOutcome {
    #[serde(default)]
    pub field: String,
    #[serde(rename = "fieldLabel", default)]
    pub field_label: String,
    #[serde(default)]
    pub goal: DiscoveryOutcomeGoal,
    #[serde(rename = "mappedField", default)]
    pub mapped_field: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DiscoveryModelCard {
    #[serde(rename = "contactEmail", default)]
    pub contact_email: String,
    #[serde(rename = "contactName", default)]
    pub contact_name: String,
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub sections: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DiscoveryModelField {
    #[serde(rename = "isDisparateImpact", default)]
    pub is_disparate_impact: bool,
    #[serde(rename = "isSensitive", default)]
    pub is_sensitive: bool,
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub r#type: DiscoveryModelFieldType,
    #[serde(default)]
    pub values: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DiscoveryModelTransform {
    #[serde(default)]
    pub config: String,
    #[serde(rename = "sourceFieldNames", default)]
    pub source_field_names: Vec<String>,
    #[serde(rename = "targetFieldNames", default)]
    pub target_field_names: Vec<String>,
    #[serde(default)]
    pub r#type: DiscoveryAIModelTransformationType,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DiscoveryPrescribableField {
    #[serde(rename = "customDefinitions", default)]
    pub custom_definitions: Vec<DiscoveryCustomPrescribableFieldDefinition>,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DiscoveryStoryOutcome {
    #[serde(rename = "failureValue", default)]
    pub failure_value: String,
    #[serde(default)]
    pub field: String,
    #[serde(default)]
    pub goal: DiscoveryStoryOutcomeGoal,
    #[serde(default)]
    pub label: String,
    #[serde(rename = "successValue", default)]
    pub success_value: String,
    #[serde(default)]
    pub r#type: DiscoveryStoryOutcomeType,
}

