#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: <https://github.com/forcedotcom/wsdl>
//!
//! DO NOT EDIT - This file is automatically generated

//! Field Mappings, Field Restrictions, Field Configurations

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FieldInstance {
    #[serde(rename = "fieldInstanceProperties", default)]
    pub field_instance_properties: Vec<FieldInstanceProperty>,
    #[serde(rename = "fieldItem", default)]
    pub field_item: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub identifier: Option<String>,
    #[serde(
        rename = "visibilityRule",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub visibility_rule: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FieldInstanceProperty {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FieldMapping {
    #[serde(rename = "SObjectType", default)]
    pub s_object_type: String,
    #[serde(rename = "developerName", default)]
    pub developer_name: String,
    #[serde(rename = "fieldMappingRows", default)]
    pub field_mapping_rows: Vec<FieldMappingRow>,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FieldMappingField {
    #[serde(rename = "dataServiceField", default)]
    pub data_service_field: String,
    #[serde(rename = "dataServiceObjectName", default)]
    pub data_service_object_name: String,
    #[serde(default)]
    pub priority: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FieldMappingRow {
    #[serde(rename = "SObjectType", default)]
    pub s_object_type: String,
    #[serde(rename = "fieldMappingFields", default)]
    pub field_mapping_fields: Vec<FieldMappingField>,
    #[serde(rename = "fieldName", default)]
    pub field_name: String,
    #[serde(rename = "mappingOperation", default)]
    pub mapping_operation: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FieldOverride {
    #[serde(default)]
    pub field: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub formula: Option<String>,
    #[serde(
        rename = "literalValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub literal_value: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FieldRestrictionRule {
    #[serde(default)]
    pub active: bool,
    #[serde(default)]
    pub classification: Vec<String>,
    #[serde(
        rename = "classificationType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub classification_type: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "enforcementType", default)]
    pub enforcement_type: serde_json::Value,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(rename = "recordFilter", default)]
    pub record_filter: String,
    #[serde(rename = "targetEntity", default)]
    pub target_entity: String,
    #[serde(rename = "userCriteria", default)]
    pub user_criteria: String,
    #[serde(default)]
    pub version: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FieldSetItem {
    #[serde(
        rename = "alternativeDisplayFormat",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub alternative_display_format: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub field: Option<String>,
    #[serde(
        rename = "isFieldManaged",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_field_managed: Option<bool>,
    #[serde(
        rename = "isRequired",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_required: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FieldSetTranslation {
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FieldValue {
    #[serde(default)]
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<serde_json::Value>,
}
