#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: https://github.com/forcedotcom/wsdl
//!
//! DO NOT EDIT - This file is automatically generated

//! Flow definitions and process automation

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowCollectionProcessorType {
    #[default]
    SortCollectionProcessor,
    RecommendationMapCollectionProcessor,
    FilterCollectionProcessor,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowExperimentFallbackMode {
    #[default]
    BestPerformer,
    Randomize,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowTransformValueActionType {
    #[default]
    Map,
    Count,
    Sum,
    GetItemByIndex,
    InnerJoin,
    InvocableAction,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowExperimentType {
    #[default]
    Random,
    Manual,
    Automatic,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowTestActivationStatus {
    #[default]
    Active,
    Inactive,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowAssignmentOperator {
    #[default]
    None,
    Assign,
    Add,
    Subtract,
    AddItem,
    RemoveFirst,
    RemoveBeforeFirst,
    RemoveAfterFirst,
    RemoveAll,
    AddAtStart,
    RemoveUncommon,
    AssignCount,
    RemovePosition,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowRunAsUser {
    #[default]
    TriggeringUser,
    DefaultWorkflowUser,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowEntryType {
    #[default]
    Always,
    AfterCompletion,
    Never,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowScheduledPathType {
    #[default]
    AsyncAfterCommit,
    ApprovalRecall,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowScheduledPathTimeSource {
    #[default]
    RecordTriggerEvent,
    RecordField,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowStageStepAssigneeType {
    #[default]
    User,
    Group,
    Queue,
    Invalid,
    Resource,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowWaitInteractionType {
    #[default]
    SmsResponse,
    WhatsappResponse,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowNodeGroupType {
    #[default]
    generic,
    rpa,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowScreenFieldType {
    #[default]
    DisplayText,
    InputField,
    LargeTextArea,
    PasswordField,
    RadioButtons,
    DropdownBox,
    MultiSelectCheckboxes,
    MultiSelectPicklist,
    ComponentInstance,
    ComponentInput,
    ComponentChoice,
    ComponentMultiChoice,
    ComponentDisplay,
    Repeater,
    RegionContainer,
    Region,
    ObjectProvided,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowStartFrequency {
    #[default]
    OnActivate,
    Once,
    Daily,
    Weekly,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowScheduledPathOffsetUnit {
    #[default]
    Hours,
    Days,
    Minutes,
    Months,
    Weeks,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowTriggerType {
    #[default]
    None,
    Scheduled,
    RecordBeforeSave,
    RecordBeforeDelete,
    RecordAfterSave,
    PlatformEvent,
    EventDrivenJourney,
    Segment,
    DataCloudDataChange,
    FormSubmissionEvent,
    Capability,
    AutomationEvent,
    ExternalSystemChange,
    DataGraphDataChange,
    Activation,
    AdminAutomationEvent,
    BroadcastNoTrigger,
    OnDemandNoTrigger,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowEnvironment {
    #[default]
    Default,
    Slack,
    Offline,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowScreenFieldInputsRevisited {
    #[default]
    UseStoredValues,
    ResetValues,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowAttributeType {
    #[default]
    LlmPrompt,
    LlmDescription,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowTestParameterType {
    #[default]
    InputTriggeringRecordInitial,
    InputTriggeringRecordUpdated,
    ScheduledPath,
    InputVariable,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowInputConfiguratorMode {
    #[default]
    Custom,
    Resource,
    Transform,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowElementSubtype {
    #[default]
    SortCollectionProcessor,
    RecommendationMapCollectionProcessor,
    FilterCollectionProcessor,
    WaitDate,
    WaitUntilEvent,
    WaitAttribute,
    WaitDuration,
    InteractiveStep,
    BackgroundStep,
    MuleSoftStep,
    ManagedContentRoleInteractiveStep,
    ManagedContentVariantSetLockBackgroundStep,
    ManagedContentVariantSetReadyBackgroundStep,
    ManagedContentVariantAutoPublishBackgroundStep,
    ManagedContentVariantAutoUnpublishBackgroundStep,
    AddPromptInstructions,
    ApprovalStep,
    AgxBackgroundStep,
    AgxInteractiveStep,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowVersionStatus {
    #[default]
    Active,
    Draft,
    Obsolete,
    InvalidDraft,
    UnderReview,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowValueMappingType {
    #[default]
    FirstEntry,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowComplexValueType {
    #[default]
    JoinDefinition,
    FieldReference,
    ResourceDescriptor,
    ResourceAnnotationMap,
    ComplexObjectFieldDetails,
    FlowDataCloudId,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowDataType {
    #[default]
    Currency,
    Date,
    Number,
    String,
    Boolean,
    SObject,
    DateTime,
    Time,
    Picklist,
    Multipicklist,
    Apex,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowRunInMode {
    #[default]
    DefaultMode,
    SystemModeWithSharing,
    SystemModeWithoutSharing,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowProcessType {
    #[default]
    AutoLaunchedFlow,
    Flow,
    Workflow,
    CustomEvent,
    InvocableProcess,
    LoginFlow,
    ActionPlan,
    JourneyBuilderIntegration,
    UserProvisioningFlow,
    Survey,
    SurveyEnrich,
    Appointments,
    FSCLending,
    DigitalForm,
    FieldServiceMobile,
    OrchestrationFlow,
    FieldServiceWeb,
    TransactionSecurityFlow,
    ContactRequestFlow,
    ManagedContentFlow,
    CheckoutFlow,
    CartAsyncFlow,
    DataCaptureFlow,
    CustomerLifecycle,
    Journey,
    RecommendationStrategy,
    Orchestrator,
    RoutingFlow,
    ServiceCatalogItemFlow,
    EvaluationFlow,
    LoyaltyManagementFlow,
    ManagedContentAuthoringWorkflow,
    ActionCadenceAutolaunchedFlow,
    ActionCadenceStepFlow,
    IndicatorResultFlow,
    IndividualObjectLinkingFlow,
    PromptFlow,
    ApprovalWorkflow,
    DcvrFrameworkDataCaptureFlow,
    ActivityObjectMatchingFlow,
    ActionableEventManagementFlow,
    StageManagementEvaluationFlow,
    IdentityUserRegistrationFlow,
    AgxBackgroundFlow,
    AgxScreenDataFlow,
    AgxScreenFlow,
    AgxOrchestrationFlow,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowComparisonOperator {
    #[default]
    None,
    EqualTo,
    NotEqualTo,
    GreaterThan,
    LessThan,
    GreaterThanOrEqualTo,
    LessThanOrEqualTo,
    StartsWith,
    EndsWith,
    Contains,
    IsNull,
    IsChanged,
    WasSet,
    WasSelected,
    WasVisited,
    In,
    NotIn,
    IsBlank,
    IsEmpty,
    HasError,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowRecordFilterOperator {
    #[default]
    EqualTo,
    NotEqualTo,
    GreaterThan,
    LessThan,
    GreaterThanOrEqualTo,
    LessThanOrEqualTo,
    StartsWith,
    EndsWith,
    Contains,
    IsNull,
    IsChanged,
    In,
    NotIn,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowTransactionModel {
    #[default]
    Automatic,
    NewTransaction,
    CurrentTransaction,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowRegionContainerType {
    #[default]
    SectionWithHeader,
    SectionWithoutHeader,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowTestPoint {
    #[serde(default)]
    pub assertions: Vec<FlowTestAssertion>,
    #[serde(rename = "elementApiName", default)]
    pub element_api_name: String,
    #[serde(default)]
    pub parameters: Vec<FlowTestParameter>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowCategoryItems {
    #[serde(default)]
    pub flow: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowTestParameter {
    #[serde(rename = "leftValueReference", default)]
    pub left_value_reference: String,
    #[serde(default)]
    pub r#type: FlowTestParameterType,
    #[serde(default)]
    pub value: FlowTestReferenceOrValue,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProcessFlowMigration {
    #[serde(rename = "destinationFlowDefinition", default)]
    pub destination_flow_definition: String,
    #[serde(rename = "destinationFlowVersion", default)]
    pub destination_flow_version: String,
    #[serde(rename = "developerName", default)]
    pub developer_name: String,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(rename = "migratedCriteriaLabel", default)]
    pub migrated_criteria_label: String,
    #[serde(rename = "migratedCriteriaName", default)]
    pub migrated_criteria_name: String,
    #[serde(rename = "processVersion", default)]
    pub process_version: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowOrchestrationStageTranslation {
    #[serde(default)]
    pub name: String,
    #[serde(rename = "stageLabel", default)]
    pub stage_label: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowTestAssertion {
    #[serde(default)]
    pub conditions: Vec<FlowTestCondition>,
    #[serde(rename = "errorMessage", default)]
    pub error_message: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowScreenTranslation {
    #[serde(rename = "backButtonLabel", default)]
    pub back_button_label: String,
    #[serde(default)]
    pub fields: Vec<FlowScreenFieldTranslation>,
    #[serde(rename = "helpText", default)]
    pub help_text: String,
    #[serde(default)]
    pub name: String,
    #[serde(rename = "nextOrFinishButtonLabel", default)]
    pub next_or_finish_button_label: String,
    #[serde(rename = "pauseButtonLabel", default)]
    pub pause_button_label: String,
    #[serde(rename = "pausedText", default)]
    pub paused_text: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowStageTranslation {
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowOrchestrationStepTranslation {
    #[serde(default)]
    pub name: String,
    #[serde(rename = "stepLabel", default)]
    pub step_label: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowComplexLiteralTranslation {
    #[serde(rename = "customAspectKey", default)]
    pub custom_aspect_key: String,
    #[serde(default)]
    pub value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowIcon {
    #[serde(rename = "iconName", default)]
    pub icon_name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowInputValidationRule {
    #[serde(rename = "errorMessage", default)]
    pub error_message: String,
    #[serde(rename = "formulaExpression", default)]
    pub formula_expression: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowCustomProperty {
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub value: FlowElementReferenceOrValue,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowMetadataValue {
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub value: FlowElementReferenceOrValue,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowCoverageWarning {
    #[serde(rename = "flowId", default)]
    pub flow_id: String,
    #[serde(rename = "flowName", default)]
    pub flow_name: String,
    #[serde(rename = "flowNamespace", default)]
    pub flow_namespace: String,
    #[serde(default)]
    pub message: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowChoiceUserInputTranslation {
    #[serde(rename = "promptText", default)]
    pub prompt_text: String,
    #[serde(rename = "validationRule", default)]
    pub validation_rule: FlowInputValidationRuleTranslation,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowTranslation {
    #[serde(default)]
    pub choices: Vec<FlowChoiceTranslation>,
    #[serde(rename = "customErrorMessages", default)]
    pub custom_error_messages: Vec<FlowCustomErrorMessageTranslation>,
    #[serde(rename = "fullName", default)]
    pub full_name: String,
    #[serde(default)]
    pub label: String,
    #[serde(rename = "orchestrationStages", default)]
    pub orchestration_stages: Vec<FlowOrchestrationStageTranslation>,
    #[serde(rename = "orchestrationSteps", default)]
    pub orchestration_steps: Vec<FlowOrchestrationStepTranslation>,
    #[serde(default)]
    pub screens: Vec<FlowScreenTranslation>,
    #[serde(default)]
    pub stages: Vec<FlowStageTranslation>,
    #[serde(rename = "textTemplates", default)]
    pub text_templates: Vec<FlowTextTemplateTranslation>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowTextTemplateTranslation {
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub text: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowScreenFieldStyleProperties {
    #[serde(rename = "styleSettings", default)]
    pub style_settings: Vec<serde_json::Value>,
    #[serde(rename = "verticalAlignment", default)]
    pub vertical_alignment: FlowElementReferenceOrValue,
    #[serde(default)]
    pub width: FlowElementReferenceOrValue,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowCustomErrorMessageTranslation {
    #[serde(rename = "developerName", default)]
    pub developer_name: String,
    #[serde(rename = "errorMessage", default)]
    pub error_message: String,
    #[serde(default)]
    pub field: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowCategory {
    #[serde(default)]
    pub description: String,
    #[serde(rename = "flowCategoryItems", default)]
    pub flow_category_items: Vec<FlowCategoryItems>,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowChoiceTranslation {
    #[serde(rename = "choiceText", default)]
    pub choice_text: String,
    #[serde(default)]
    pub name: String,
    #[serde(rename = "userInput", default)]
    pub user_input: FlowChoiceUserInputTranslation,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowFerovTranslation {
    #[serde(rename = "complexValues", default)]
    pub complex_values: Vec<FlowComplexLiteralTranslation>,
    #[serde(rename = "stringValue", default)]
    pub string_value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowTest {
    #[serde(default)]
    pub description: String,
    #[serde(rename = "flowApiName", default)]
    pub flow_api_name: String,
    #[serde(rename = "flowTestFlowVersions", default)]
    pub flow_test_flow_versions: Vec<FlowTestFlowVersion>,
    #[serde(default)]
    pub label: String,
    #[serde(rename = "testPoints", default)]
    pub test_points: Vec<FlowTestPoint>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowTestReferenceOrValue {
    #[serde(rename = "booleanValue", default)]
    pub boolean_value: bool,
    #[serde(rename = "dateTimeValue", default)]
    pub date_time_value: String,
    #[serde(rename = "dateValue", default)]
    pub date_value: String,
    #[serde(rename = "numberValue", default)]
    pub number_value: f64,
    #[serde(rename = "sobjectValue", default)]
    pub sobject_value: String,
    #[serde(rename = "stringValue", default)]
    pub string_value: String,
    #[serde(rename = "timeValue", default)]
    pub time_value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowScreenFieldTranslation {
    #[serde(rename = "fieldText", default)]
    pub field_text: String,
    #[serde(rename = "helpText", default)]
    pub help_text: String,
    #[serde(rename = "inputParameters", default)]
    pub input_parameters: Vec<FlowInputParameterTranslation>,
    #[serde(default)]
    pub name: String,
    #[serde(rename = "validationRule", default)]
    pub validation_rule: FlowInputValidationRuleTranslation,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct Flow {
    #[serde(rename = "actionCalls", default)]
    pub action_calls: Vec<serde_json::Value>,
    #[serde(rename = "apexPluginCalls", default)]
    pub apex_plugin_calls: Vec<serde_json::Value>,
    #[serde(rename = "apiVersion", default)]
    pub api_version: f64,
    #[serde(rename = "areMetricsLoggedToDataCloud", default)]
    pub are_metrics_logged_to_data_cloud: bool,
    #[serde(default)]
    pub assignments: Vec<serde_json::Value>,
    #[serde(default)]
    pub choices: Vec<serde_json::Value>,
    #[serde(rename = "collectionProcessors", default)]
    pub collection_processors: Vec<serde_json::Value>,
    #[serde(default)]
    pub constants: Vec<serde_json::Value>,
    #[serde(rename = "customErrors", default)]
    pub custom_errors: Vec<serde_json::Value>,
    #[serde(rename = "customProperties", default)]
    pub custom_properties: Vec<FlowCustomProperty>,
    #[serde(rename = "dataSpace", default)]
    pub data_space: String,
    #[serde(default)]
    pub decisions: Vec<serde_json::Value>,
    #[serde(default)]
    pub description: String,
    #[serde(rename = "dynamicChoiceSets", default)]
    pub dynamic_choice_sets: Vec<serde_json::Value>,
    #[serde(default)]
    pub environments: Vec<FlowEnvironment>,
    #[serde(rename = "exitRules", default)]
    pub exit_rules: Vec<serde_json::Value>,
    #[serde(default)]
    pub experiments: Vec<serde_json::Value>,
    #[serde(default)]
    pub formulas: Vec<serde_json::Value>,
    #[serde(default)]
    pub groups: Vec<serde_json::Value>,
    #[serde(rename = "interviewLabel", default)]
    pub interview_label: String,
    #[serde(rename = "isAdditionalPermissionRequiredToRun", default)]
    pub is_additional_permission_required_to_run: bool,
    #[serde(rename = "isOverridable", default)]
    pub is_overridable: bool,
    #[serde(rename = "isTemplate", default)]
    pub is_template: bool,
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub loops: Vec<serde_json::Value>,
    #[serde(rename = "migratedFromWorkflowRuleName", default)]
    pub migrated_from_workflow_rule_name: String,
    #[serde(rename = "orchestratedStages", default)]
    pub orchestrated_stages: Vec<serde_json::Value>,
    #[serde(rename = "overriddenFlow", default)]
    pub overridden_flow: String,
    #[serde(rename = "processMetadataValues", default)]
    pub process_metadata_values: Vec<FlowMetadataValue>,
    #[serde(rename = "processType", default)]
    pub process_type: FlowProcessType,
    #[serde(rename = "recordCreates", default)]
    pub record_creates: Vec<serde_json::Value>,
    #[serde(rename = "recordDeletes", default)]
    pub record_deletes: Vec<serde_json::Value>,
    #[serde(rename = "recordLookups", default)]
    pub record_lookups: Vec<serde_json::Value>,
    #[serde(rename = "recordRollbacks", default)]
    pub record_rollbacks: Vec<serde_json::Value>,
    #[serde(rename = "recordUpdates", default)]
    pub record_updates: Vec<serde_json::Value>,
    #[serde(rename = "runInMode", default)]
    pub run_in_mode: FlowRunInMode,
    #[serde(default)]
    pub screens: Vec<serde_json::Value>,
    #[serde(rename = "sourceTemplate", default)]
    pub source_template: String,
    #[serde(default)]
    pub stages: Vec<serde_json::Value>,
    #[serde(default)]
    pub start: serde_json::Value,
    #[serde(rename = "startElementReference", default)]
    pub start_element_reference: String,
    #[serde(default)]
    pub status: FlowVersionStatus,
    #[serde(default)]
    pub steps: Vec<serde_json::Value>,
    #[serde(default)]
    pub subflows: Vec<serde_json::Value>,
    #[serde(rename = "textTemplates", default)]
    pub text_templates: Vec<serde_json::Value>,
    #[serde(rename = "timeZoneSidKey", default)]
    pub time_zone_sid_key: String,
    #[serde(default)]
    pub transforms: Vec<serde_json::Value>,
    #[serde(rename = "triggerOrder", default)]
    pub trigger_order: f64,
    #[serde(default)]
    pub variables: Vec<serde_json::Value>,
    #[serde(default)]
    pub waits: Vec<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowInputValidationRuleTranslation {
    #[serde(rename = "errorMessage", default)]
    pub error_message: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowDefinitionTranslation {
    #[serde(default)]
    pub flows: Vec<FlowTranslation>,
    #[serde(rename = "fullName", default)]
    pub full_name: String,
    #[serde(default)]
    pub label: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowDefinition {
    #[serde(rename = "activeVersionNumber", default)]
    pub active_version_number: f64,
    #[serde(default)]
    pub description: String,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowCoverageResult {
    #[serde(rename = "elementsNotCovered", default)]
    pub elements_not_covered: Vec<String>,
    #[serde(rename = "flowId", default)]
    pub flow_id: String,
    #[serde(rename = "flowName", default)]
    pub flow_name: String,
    #[serde(rename = "flowNamespace", default)]
    pub flow_namespace: String,
    #[serde(rename = "numElements", default)]
    pub num_elements: f64,
    #[serde(rename = "numElementsNotCovered", default)]
    pub num_elements_not_covered: f64,
    #[serde(rename = "processType", default)]
    pub process_type: FlowProcessType,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowBaseElement {
    #[serde(rename = "processMetadataValues", default)]
    pub process_metadata_values: Vec<FlowMetadataValue>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowInputParameterTranslation {
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub value: FlowFerovTranslation,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowSchedule {
    #[serde(default)]
    pub frequency: FlowStartFrequency,
    #[serde(rename = "startDate", default)]
    pub start_date: String,
    #[serde(rename = "startTime", default)]
    pub start_time: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowTestFlowVersion {
    #[serde(rename = "flowTestActivationStatus", default)]
    pub flow_test_activation_status: FlowTestActivationStatus,
    #[serde(rename = "versionNumber", default)]
    pub version_number: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowElementReferenceOrValue {
    #[serde(rename = "apexValue", default)]
    pub apex_value: String,
    #[serde(rename = "booleanValue", default)]
    pub boolean_value: bool,
    #[serde(rename = "collectionElements", default)]
    pub collection_elements: Vec<Box<FlowElementReferenceOrValue>>,
    #[serde(rename = "complexValue", default)]
    pub complex_value: String,
    #[serde(rename = "complexValueType", default)]
    pub complex_value_type: FlowComplexValueType,
    #[serde(rename = "dateTimeValue", default)]
    pub date_time_value: String,
    #[serde(rename = "dateValue", default)]
    pub date_value: String,
    #[serde(rename = "elementReference", default)]
    pub element_reference: String,
    #[serde(rename = "formulaDataType", default)]
    pub formula_data_type: FlowDataType,
    #[serde(rename = "formulaExpression", default)]
    pub formula_expression: String,
    #[serde(rename = "inputConfiguratorMode", default)]
    pub input_configurator_mode: FlowInputConfiguratorMode,
    #[serde(rename = "numberValue", default)]
    pub number_value: f64,
    #[serde(rename = "setupReference", default)]
    pub setup_reference: String,
    #[serde(rename = "setupReferenceType", default)]
    pub setup_reference_type: String,
    #[serde(rename = "sobjectValue", default)]
    pub sobject_value: String,
    #[serde(rename = "stringValue", default)]
    pub string_value: String,
    #[serde(rename = "timeValue", default)]
    pub time_value: String,
    #[serde(default)]
    pub transform: serde_json::Value,
    #[serde(rename = "transformValueReference", default)]
    pub transform_value_reference: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct FlowTestCondition {
    #[serde(rename = "leftValueReference", default)]
    pub left_value_reference: String,
    #[serde(default)]
    pub operator: FlowComparisonOperator,
    #[serde(rename = "rightValue", default)]
    pub right_value: FlowTestReferenceOrValue,
}
