#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: <https://github.com/forcedotcom/wsdl>
//!
//! DO NOT EDIT - This file is automatically generated

//! Home Page Components, Home Page Layouts

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct HomePageComponent {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub height: Option<f64>,
    #[serde(default)]
    pub links: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub page: Option<String>,
    #[serde(rename = "pageComponentType", default)]
    pub page_component_type: serde_json::Value,
    #[serde(rename = "showLabel", default, skip_serializing_if = "Option::is_none")]
    pub show_label: Option<bool>,
    #[serde(
        rename = "showScrollbars",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub show_scrollbars: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub width: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct HomePageLayout {
    #[serde(rename = "narrowComponents", default)]
    pub narrow_components: Vec<String>,
    #[serde(rename = "wideComponents", default)]
    pub wide_components: Vec<String>,
}
