#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: https://github.com/forcedotcom/wsdl
//!
//! DO NOT EDIT - This file is automatically generated

//! Home Page Components, Home Page Layouts

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct HomePageComponent {
    #[serde(default)]
    pub body: String,
    #[serde(default)]
    pub height: f64,
    #[serde(default)]
    pub links: Vec<String>,
    #[serde(default)]
    pub page: String,
    #[serde(rename = "pageComponentType", default)]
    pub page_component_type: serde_json::Value,
    #[serde(rename = "showLabel", default)]
    pub show_label: bool,
    #[serde(rename = "showScrollbars", default)]
    pub show_scrollbars: bool,
    #[serde(default)]
    pub width: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct HomePageLayout {
    #[serde(rename = "narrowComponents", default)]
    pub narrow_components: Vec<String>,
    #[serde(rename = "wideComponents", default)]
    pub wide_components: Vec<String>,
}
