#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: <https://github.com/forcedotcom/wsdl>
//!
//! DO NOT EDIT - This file is automatically generated

//! Industry Cloud types (Health, Insurance, Manufacturing, Automotive)

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum CareLimitTypeMetricType {
    #[default]
    Money,
    Percentage,
    Amount,
    Text,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum CareProviderAfflType {
    #[default]
    HospitalAffiliation,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum InsPolicyLifecycleProcess {
    #[default]
    Renew,
    Repurpose,
    Endorse,
    Cancel,
    Bulk_Renew,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum InsRatePlanCmsnConfigCalcType {
    #[default]
    Flat,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum InstallValidationStatus {
    #[default]
    NO_ERRORS_DETECTED,
    BETA_INSTALL_INTO_PRODUCTION_ORG,
    CANNOT_INSTALL_EARLIER_VERSION,
    CANNOT_UPGRADE_BETA,
    CANNOT_UPGRADE_UNMANAGED,
    DEPRECATED_INSTALL_PACKAGE,
    EXTENSIONS_ON_LOCAL_PACKAGES,
    PACKAGE_NOT_INSTALLED,
    PACKAGE_HAS_IN_DEV_EXTENSIONS,
    INSTALL_INTO_DEV_ORG,
    NO_ACCESS,
    PACKAGING_DISABLED,
    PACKAGING_NO_ACCESS,
    PACKAGE_UNAVAILABLE,
    PACKAGE_UNAVAILABLE_CRC,
    PACKAGE_UNAVAILABLE_ZIP,
    UNINSTALL_IN_PROGRESS,
    UNKNOWN_ERROR,
    NAMESPACE_COLLISION,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CareLimitType {
    #[serde(
        rename = "isProtected",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_protected: Option<bool>,
    #[serde(rename = "limitType", default, skip_serializing_if = "Option::is_none")]
    pub limit_type: Option<String>,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(
        rename = "metricType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub metric_type: Option<CareLimitTypeMetricType>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CareProviderAfflRoleConfig {
    #[serde(
        rename = "affiliationType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub affiliation_type: Option<CareProviderAfflType>,
    #[serde(
        rename = "isProtected",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_protected: Option<bool>,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(
        rename = "providerRole",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub provider_role: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CareProviderSearchConfig {
    #[serde(rename = "isActive", default, skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(
        rename = "isProtected",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_protected: Option<bool>,
    #[serde(rename = "mappedObject", default)]
    pub mapped_object: serde_json::Value,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(
        rename = "sourceField",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub source_field: Option<String>,
    #[serde(
        rename = "targetField",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub target_field: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CareRequestConfiguration {
    #[serde(rename = "careRequestRecordType", default)]
    pub care_request_record_type: String,
    #[serde(rename = "careRequestRecords", default)]
    pub care_request_records: Vec<CareRequestRecords>,
    #[serde(rename = "careRequestType", default)]
    pub care_request_type: String,
    #[serde(rename = "isActive", default, skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(
        rename = "isDefaultRecordType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_default_record_type: Option<bool>,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CareRequestRecords {
    #[serde(rename = "careRequestRecord", default)]
    pub care_request_record: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct CareSystemFieldMapping {
    #[serde(
        rename = "externalIdField",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub external_id_field: Option<String>,
    #[serde(rename = "isActive", default, skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(
        rename = "isProtected",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_protected: Option<bool>,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(default)]
    pub role: serde_json::Value,
    #[serde(
        rename = "sourceSystem",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub source_system: Option<String>,
    #[serde(
        rename = "targetObject",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub target_object: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct InsPlcyCoverageSpecConfig {
    #[serde(rename = "coverageSpecification", default)]
    pub coverage_specification: String,
    #[serde(rename = "isNetworkTierApplicable", default)]
    pub is_network_tier_applicable: bool,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct InsPlcyLineOfBusConfig {
    #[serde(rename = "lineOfBusiness", default)]
    pub line_of_business: String,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(rename = "termName", default)]
    pub term_name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct InsPolicyLifecycleConfig {
    #[serde(
        rename = "customContextDefinition",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub custom_context_definition: Option<String>,
    #[serde(
        rename = "customContextMapping",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub custom_context_mapping: Option<String>,
    #[serde(rename = "displayFields", default)]
    pub display_fields: String,
    #[serde(rename = "policyProcessType", default)]
    pub policy_process_type: InsPolicyLifecycleProcess,
    #[serde(
        rename = "standardContextDefinition",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub standard_context_definition: Option<String>,
    #[serde(
        rename = "standardContextMapping",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub standard_context_mapping: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct InsPolicyManagementConfig {
    #[serde(
        rename = "expectedRevExpsSetDef",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub expected_rev_exps_set_def: Option<String>,
    #[serde(default)]
    pub label: String,
    #[serde(
        rename = "premiumCalcExpsSetDef",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub premium_calc_exps_set_def: Option<String>,
    #[serde(
        rename = "stdExpectedRevExpsSetDef",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub std_expected_rev_exps_set_def: Option<String>,
    #[serde(
        rename = "stdPremiumCalcExpsSetDef",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub std_premium_calc_exps_set_def: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct InsRatePlanCmsnConfig {
    #[serde(rename = "calculationType", default)]
    pub calculation_type: InsRatePlanCmsnConfigCalcType,
    #[serde(rename = "displayFields", default)]
    pub display_fields: String,
    #[serde(rename = "ratePlanCommissionType", default)]
    pub rate_plan_commission_type: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct InsRatePlanTypeConfig {
    #[serde(rename = "displayFields", default)]
    pub display_fields: String,
    #[serde(rename = "ratePlanCommissionTypes", default)]
    pub rate_plan_commission_types: String,
    #[serde(rename = "ratePlanType", default)]
    pub rate_plan_type: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct InstallRequestRecord {
    #[serde(rename = "Id", default)]
    pub id: String,
}
