#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: <https://github.com/forcedotcom/wsdl>
//!
//! DO NOT EDIT - This file is automatically generated

//! Loyalty Cloud, Programs, Benefits, Vouchers

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum BenefitActionDataType {
    #[default]
    String,
    Date,
    DateTime,
    Boolean,
    Picklist,
    EntityPicklist,
    Number,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum LoyaltyPgmProcActParamOper {
    #[default]
    Equals,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum LoyaltyPgmProcActParamType {
    #[default]
    Literal,
    Parameter,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum LoyaltyPgmProcActionType {
    #[default]
    CreditPoints,
    DebitPoints,
    IssueVoucher,
    IncreaseUsageForCumulativePromotion,
    UpdateUsageForCumulativePromotion,
    AssignParameterValues,
    RunFlow,
    GetOutputsFromDecisionTable,
    UpdatePointBalance,
    GetMemberPointBalance,
    GetMemberTier,
    GetMemberAttributesValues,
    UpdateCurrentValueForMemberAttribute,
    RunProgramProcess,
    Crud,
    AssignBadgeToMember,
    CheckMemberBadgeAssignment,
    ChangeMemberTier,
    GetMemberPromotions,
    RedeemVoucher,
    SendMail,
    IssueExtendedReward,
    GetCustomerPromotionAttrValue,
    UpdateCustomerPromotionAttrValue,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum LoyaltyPgmProcCondOperator {
    #[default]
    Equals,
    NotEquals,
    GreaterThan,
    GreaterThanOrEquals,
    LessThan,
    LessThanOrEquals,
    Contains,
    DoesNotContain,
    IsNull,
    IsNotNull,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum LoyaltyPgmProcCondType {
    #[default]
    Literal,
    Parameter,
    Formula,
    Lookup,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum LoyaltyPgmProcCrudActType {
    #[default]
    create,
    update,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum LoyaltyPgmProcExecutionType {
    #[default]
    RealTime,
    Batch,
    BatchAndRealTime,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum LoyaltyPgmProcParmDataType {
    #[default]
    Text,
    Numeric,
    Date,
    DateTime,
    Sobject,
    Boolean,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum LoyaltyPgmProcParmType {
    #[default]
    Variable,
    Constant,
    Formula,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum LoyaltyPgmProcRuleStatus {
    #[default]
    Draft,
    Active,
    Inactive,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum LoyaltyPgmProcRuleType {
    #[default]
    Condition,
    Action,
    ConditionGroup,
    DefaultPath,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum LoyaltyPgmProcStatus {
    #[default]
    Draft,
    Active,
    Inactive,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BenefitAction {
    #[serde(rename = "benefitActionParameters", default)]
    pub benefit_action_parameters: Vec<BenefitActionParameter>,
    #[serde(default)]
    pub description: String,
    #[serde(rename = "flowDefinition", default)]
    pub flow_definition: String,
    #[serde(rename = "isActive", default)]
    pub is_active: bool,
    #[serde(rename = "isBenefitExpirationAllowed", default)]
    pub is_benefit_expiration_allowed: bool,
    #[serde(rename = "isBenefitUpdateAllowed", default)]
    pub is_benefit_update_allowed: bool,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(rename = "memberBenefitVariableName", default)]
    pub member_benefit_variable_name: String,
    #[serde(rename = "processType", default)]
    pub process_type: String,
    #[serde(default)]
    pub r#type: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BenefitActionParameter {
    #[serde(rename = "dataType", default)]
    pub data_type: BenefitActionDataType,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(default)]
    pub name: String,
    #[serde(rename = "objectName", default)]
    pub object_name: String,
    #[serde(rename = "parameterValues", default)]
    pub parameter_values: Vec<BenefitActionParameterValue>,
    #[serde(rename = "picklistName", default)]
    pub picklist_name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct BenefitActionParameterValue {
    #[serde(rename = "parameterValue", default)]
    pub parameter_value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct LoyaltyProgramProcess {
    #[serde(default)]
    pub description: String,
    #[serde(rename = "executionType", default)]
    pub execution_type: LoyaltyPgmProcExecutionType,
    #[serde(rename = "journalSubType", default)]
    pub journal_sub_type: String,
    #[serde(rename = "journalType", default)]
    pub journal_type: String,
    #[serde(rename = "loyaltyTierGroup", default)]
    pub loyalty_tier_group: String,
    #[serde(default)]
    pub parameters: Vec<LoyaltyProgramProcessParameter>,
    #[serde(rename = "processName", default)]
    pub process_name: String,
    #[serde(rename = "processType", default)]
    pub process_type: String,
    #[serde(default)]
    pub rules: Vec<LoyaltyProgramProcessRule>,
    #[serde(default)]
    pub status: LoyaltyPgmProcStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct LoyaltyProgramProcessAction {
    #[serde(rename = "actionName", default)]
    pub action_name: String,
    #[serde(rename = "actionParameters", default)]
    pub action_parameters: Vec<LoyaltyProgramProcessActionParameter>,
    #[serde(rename = "actionType", default)]
    pub action_type: LoyaltyPgmProcActionType,
    #[serde(rename = "crudActionType", default)]
    pub crud_action_type: LoyaltyPgmProcCrudActType,
    #[serde(rename = "decisionTable", default)]
    pub decision_table: String,
    #[serde(rename = "decisionTableDatasetLink", default)]
    pub decision_table_dataset_link: String,
    #[serde(rename = "entityApiName", default)]
    pub entity_api_name: String,
    #[serde(rename = "flowDefinition", default)]
    pub flow_definition: String,
    #[serde(rename = "loyaltyProgramProcess", default)]
    pub loyalty_program_process: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct LoyaltyProgramProcessActionParameter {
    #[serde(default)]
    pub operator: LoyaltyPgmProcActParamOper,
    #[serde(rename = "parameterName", default)]
    pub parameter_name: String,
    #[serde(rename = "sequenceNumber", default)]
    pub sequence_number: f64,
    #[serde(default)]
    pub value: String,
    #[serde(rename = "valueType", default)]
    pub value_type: LoyaltyPgmProcActParamType,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct LoyaltyProgramProcessCondition {
    #[serde(rename = "conditionCriteria", default)]
    pub condition_criteria: String,
    #[serde(rename = "conditionFilterCriteria", default)]
    pub condition_filter_criteria: Vec<LoyaltyProgramProcessConditionFilterCriteria>,
    #[serde(rename = "conditionName", default)]
    pub condition_name: String,
    #[serde(rename = "conditionType", default)]
    pub condition_type: LoyaltyPgmProcRuleType,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct LoyaltyProgramProcessConditionFilterCriteria {
    #[serde(default)]
    pub operator: LoyaltyPgmProcCondOperator,
    #[serde(default)]
    pub sequence: f64,
    #[serde(rename = "sourceFieldName", default)]
    pub source_field_name: String,
    #[serde(default)]
    pub value: String,
    #[serde(rename = "valueType", default)]
    pub value_type: LoyaltyPgmProcCondType,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct LoyaltyProgramProcessParameter {
    #[serde(default)]
    pub condition: LoyaltyProgramProcessCondition,
    #[serde(rename = "dataType", default)]
    pub data_type: LoyaltyPgmProcParmDataType,
    #[serde(rename = "decimalPlaces", default)]
    pub decimal_places: f64,
    #[serde(default)]
    pub description: String,
    #[serde(rename = "isCollection", default)]
    pub is_collection: bool,
    #[serde(rename = "isInput", default)]
    pub is_input: bool,
    #[serde(rename = "isOutput", default)]
    pub is_output: bool,
    #[serde(rename = "objectName", default)]
    pub object_name: String,
    #[serde(rename = "parameterName", default)]
    pub parameter_name: String,
    #[serde(rename = "parameterType", default)]
    pub parameter_type: LoyaltyPgmProcParmType,
    #[serde(default)]
    pub value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct LoyaltyProgramProcessRule {
    #[serde(default)]
    pub actions: Vec<LoyaltyProgramProcessAction>,
    #[serde(default)]
    pub conditions: Vec<LoyaltyProgramProcessCondition>,
    #[serde(default)]
    pub description: String,
    #[serde(rename = "endDate", default)]
    pub end_date: String,
    #[serde(rename = "isProcessEligibilityRule", default)]
    pub is_process_eligibility_rule: bool,
    #[serde(rename = "previousRule", default)]
    pub previous_rule: String,
    #[serde(default)]
    pub promotion: String,
    #[serde(rename = "ruleName", default)]
    pub rule_name: String,
    #[serde(rename = "startDate", default)]
    pub start_date: String,
    #[serde(default)]
    pub status: LoyaltyPgmProcRuleStatus,
    #[serde(rename = "stepMappings", default)]
    pub step_mappings: Vec<LoyaltyProgramProcessRuleStepMapping>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct LoyaltyProgramProcessRuleStepMapping {
    #[serde(rename = "associatedStep", default)]
    pub associated_step: String,
    #[serde(rename = "parentStep", default)]
    pub parent_step: String,
    #[serde(default)]
    pub sequence: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct LoyaltyProgramSetup {
    #[serde(default)]
    pub label: String,
    #[serde(rename = "programProcesses", default)]
    pub program_processes: Vec<LoyaltyProgramProcess>,
}
