#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: https://github.com/forcedotcom/wsdl
//!
//! DO NOT EDIT - This file is automatically generated

//! Managed Content, Managed Topics, CMS

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum ManagedContentSpaceModuleStatusEnum {
    #[default]
    ENABLED,
    DISABLED,
    ERROR,
    INVALID,
    STANDBY,
    NOT_INSTALLED,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ManagedContentNodeType {
    #[serde(rename = "helpText", default)]
    pub help_text: String,
    #[serde(rename = "isLocalizable", default)]
    pub is_localizable: bool,
    #[serde(rename = "isRequired", default)]
    pub is_required: bool,
    #[serde(rename = "nodeLabel", default)]
    pub node_label: String,
    #[serde(rename = "nodeName", default)]
    pub node_name: String,
    #[serde(rename = "nodeType", default)]
    pub node_type: serde_json::Value,
    #[serde(rename = "placeholderText", default)]
    pub placeholder_text: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ManagedContentType {
    #[serde(default)]
    pub description: String,
    #[serde(rename = "developerName", default)]
    pub developer_name: String,
    #[serde(rename = "isMetadataContent", default)]
    pub is_metadata_content: bool,
    #[serde(rename = "managedContentNodeTypes", default)]
    pub managed_content_node_types: Vec<ManagedContentNodeType>,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ManagedContentTypeBundle {
    #[serde(default)]
    pub description: String,
    #[serde(rename = "developerName", default)]
    pub developer_name: String,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(rename = "schemaBody", default)]
    pub schema_body: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ManagedEventSubscription {
    #[serde(rename = "defaultReplay", default)]
    pub default_replay: serde_json::Value,
    #[serde(rename = "errorRecoveryReplay", default)]
    pub error_recovery_replay: serde_json::Value,
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub state: serde_json::Value,
    #[serde(rename = "topicName", default)]
    pub topic_name: String,
    #[serde(default)]
    pub version: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ManagedTopic {
    #[serde(rename = "managedTopicType", default)]
    pub managed_topic_type: String,
    #[serde(default)]
    pub name: String,
    #[serde(rename = "parentName", default)]
    pub parent_name: String,
    #[serde(default)]
    pub position: f64,
    #[serde(rename = "topicDescription", default)]
    pub topic_description: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ManagedTopics {
    #[serde(rename = "managedTopic", default)]
    pub managed_topic: Vec<ManagedTopic>,
}

