#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: https://github.com/forcedotcom/wsdl
//!
//! DO NOT EDIT - This file is automatically generated

//! Navigation Menus, Navigation Links

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct NavigationSubMenu {
    #[serde(rename = "navigationMenuItem", default)]
    pub navigation_menu_item: Vec<NavigationMenuItem>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct NavigationMenuItemBranding {
    #[serde(rename = "tileImage", default)]
    pub tile_image: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct NavigationMenuItem {
    #[serde(rename = "defaultListViewId", default)]
    pub default_list_view_id: String,
    #[serde(default)]
    pub label: String,
    #[serde(rename = "menuItemBranding", default)]
    pub menu_item_branding: NavigationMenuItemBranding,
    #[serde(default)]
    pub position: f64,
    #[serde(rename = "publiclyAvailable", default)]
    pub publicly_available: bool,
    #[serde(rename = "subMenu", default)]
    pub sub_menu: NavigationSubMenu,
    #[serde(default)]
    pub target: String,
    #[serde(rename = "targetPreference", default)]
    pub target_preference: String,
    #[serde(default)]
    pub r#type: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct NavigationMenu {
    #[serde(default)]
    pub container: String,
    #[serde(rename = "containerType", default)]
    pub container_type: String,
    #[serde(default)]
    pub label: String,
    #[serde(rename = "navigationMenuItem", default)]
    pub navigation_menu_item: Vec<NavigationMenuItem>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct NavigationLinkSet {
    #[serde(rename = "navigationMenuItem", default)]
    pub navigation_menu_item: Vec<NavigationMenuItem>,
}
