#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: <https://github.com/forcedotcom/wsdl>
//!
//! DO NOT EDIT - This file is automatically generated

//! Permission sets, profiles, and sharing rules

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum PermissionSetTabVisibility {
    #[default]
    None,
    Available,
    Visible,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum SharingModel {
    #[default]
    Private,
    Read,
    ReadSelect,
    ReadWrite,
    ReadWriteTransfer,
    FullAccess,
    ControlledByParent,
    ControlledByLeadOrContact,
    ControlledByCampaign,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct MutingPermissionSet {
    #[serde(default)]
    pub label: String,
}

/// Represents a set of permissions that can be assigned to users.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PermissionSet {
    #[serde(rename = "agentAccesses", default)]
    pub agent_accesses: Vec<PermissionSetAgentAccess>,
    #[serde(rename = "applicationVisibilities", default)]
    pub application_visibilities: Vec<PermissionSetApplicationVisibility>,
    #[serde(rename = "classAccesses", default)]
    pub class_accesses: Vec<PermissionSetApexClassAccess>,
    #[serde(rename = "customMetadataTypeAccesses", default)]
    pub custom_metadata_type_accesses: Vec<PermissionSetCustomMetadataTypeAccess>,
    #[serde(rename = "customPermissions", default)]
    pub custom_permissions: Vec<PermissionSetCustomPermissions>,
    #[serde(rename = "customSettingAccesses", default)]
    pub custom_setting_accesses: Vec<PermissionSetCustomSettingAccess>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "emailRoutingAddressAccesses", default)]
    pub email_routing_address_accesses: Vec<PermissionSetEmailRoutingAddressAccess>,
    #[serde(rename = "externalCredentialPrincipalAccesses", default)]
    pub external_credential_principal_accesses: Vec<PermissionSetExternalCredentialPrincipalAccess>,
    #[serde(rename = "externalDataSourceAccesses", default)]
    pub external_data_source_accesses: Vec<PermissionSetExternalDataSourceAccess>,
    /// List of field-level security permissions.
    #[serde(rename = "fieldPermissions", default)]
    pub field_permissions: Vec<PermissionSetFieldPermissions>,
    #[serde(rename = "flowAccesses", default)]
    pub flow_accesses: Vec<PermissionSetFlowAccess>,
    #[serde(rename = "genComputingSummaryDefAccesses", default)]
    pub gen_computing_summary_def_accesses: Vec<PermissionSetGenComputingSummaryDefAccess>,
    #[serde(
        rename = "hasActivationRequired",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub has_activation_required: Option<bool>,
    /// The label of the permission set.
    #[serde(default)]
    pub label: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub license: Option<String>,
    /// List of object-level permissions (CRUD).
    #[serde(rename = "objectPermissions", default)]
    pub object_permissions: Vec<PermissionSetObjectPermissions>,
    #[serde(rename = "pageAccesses", default)]
    pub page_accesses: Vec<PermissionSetApexPageAccess>,
    #[serde(rename = "recordTypeVisibilities", default)]
    pub record_type_visibilities: Vec<PermissionSetRecordTypeVisibility>,
    #[serde(rename = "servicePresenceStatusAccesses", default)]
    pub service_presence_status_accesses: Vec<PermissionSetServicePresenceStatusAccess>,
    #[serde(rename = "tabSettings", default)]
    pub tab_settings: Vec<PermissionSetTabSetting>,
    /// List of user permissions enabled in this set.
    #[serde(rename = "userPermissions", default)]
    pub user_permissions: Vec<PermissionSetUserPermission>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PermissionSetAgentAccess {
    #[serde(rename = "agentName", default)]
    pub agent_name: String,
    #[serde(default)]
    pub enabled: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PermissionSetApexClassAccess {
    #[serde(rename = "apexClass", default)]
    pub apex_class: String,
    #[serde(default)]
    pub enabled: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PermissionSetApexPageAccess {
    #[serde(rename = "apexPage", default)]
    pub apex_page: String,
    #[serde(default)]
    pub enabled: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PermissionSetApplicationVisibility {
    #[serde(default)]
    pub application: String,
    #[serde(default)]
    pub visible: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PermissionSetCustomMetadataTypeAccess {
    #[serde(default)]
    pub enabled: bool,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PermissionSetCustomPermissions {
    #[serde(default)]
    pub enabled: bool,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PermissionSetCustomSettingAccess {
    #[serde(default)]
    pub enabled: bool,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PermissionSetEmailRoutingAddressAccess {
    #[serde(default)]
    pub enabled: bool,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PermissionSetExternalCredentialPrincipalAccess {
    #[serde(default)]
    pub enabled: bool,
    #[serde(rename = "externalCredentialPrincipal", default)]
    pub external_credential_principal: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PermissionSetExternalDataSourceAccess {
    #[serde(default)]
    pub enabled: bool,
    #[serde(rename = "externalDataSource", default)]
    pub external_data_source: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PermissionSetFieldPermissions {
    #[serde(default)]
    pub editable: bool,
    #[serde(default)]
    pub field: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub readable: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PermissionSetFlowAccess {
    #[serde(default)]
    pub enabled: bool,
    #[serde(default)]
    pub flow: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PermissionSetGenComputingSummaryDefAccess {
    #[serde(rename = "configName", default)]
    pub config_name: String,
    #[serde(default)]
    pub enabled: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PermissionSetGroup {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(
        rename = "hasActivationRequired",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub has_activation_required: Option<bool>,
    #[serde(default)]
    pub label: String,
    #[serde(rename = "mutingPermissionSets", default)]
    pub muting_permission_sets: Vec<String>,
    #[serde(rename = "permissionSets", default)]
    pub permission_sets: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PermissionSetLicenseDefinition {
    #[serde(rename = "componentAccess", default)]
    pub component_access: serde_json::Value,
    #[serde(rename = "customObjects", default)]
    pub custom_objects: Vec<PermissionSetLicenseDefinitionCustomObject>,
    #[serde(rename = "customPermissions", default)]
    pub custom_permissions: Vec<PermissionSetLicenseDefinitionCustomPermission>,
    #[serde(rename = "defaultTrialLengthInDays", default)]
    pub default_trial_length_in_days: f64,
    #[serde(rename = "defaultTrialLicenseCount", default)]
    pub default_trial_license_count: f64,
    #[serde(default)]
    pub label: String,
    #[serde(
        rename = "userLicenseRestrictions",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub user_license_restrictions: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PermissionSetLicenseDefinitionCustomObject {
    #[serde(
        rename = "allowCreate",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub allow_create: Option<bool>,
    #[serde(
        rename = "allowDelete",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub allow_delete: Option<bool>,
    #[serde(rename = "allowRead", default, skip_serializing_if = "Option::is_none")]
    pub allow_read: Option<bool>,
    #[serde(
        rename = "allowUpdate",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub allow_update: Option<bool>,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PermissionSetLicenseDefinitionCustomPermission {
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PermissionSetObjectPermissions {
    #[serde(rename = "allowCreate", default)]
    pub allow_create: bool,
    #[serde(rename = "allowDelete", default)]
    pub allow_delete: bool,
    #[serde(rename = "allowEdit", default)]
    pub allow_edit: bool,
    #[serde(rename = "allowRead", default)]
    pub allow_read: bool,
    #[serde(rename = "modifyAllRecords", default)]
    pub modify_all_records: bool,
    #[serde(default)]
    pub object: String,
    #[serde(
        rename = "viewAllFields",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub view_all_fields: Option<bool>,
    #[serde(rename = "viewAllRecords", default)]
    pub view_all_records: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PermissionSetRecordTypeVisibility {
    #[serde(rename = "recordType", default)]
    pub record_type: String,
    #[serde(default)]
    pub visible: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PermissionSetServicePresenceStatusAccess {
    #[serde(default)]
    pub enabled: bool,
    #[serde(rename = "servicePresenceStatus", default)]
    pub service_presence_status: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PermissionSetTabSetting {
    #[serde(default)]
    pub tab: String,
    #[serde(default)]
    pub visibility: PermissionSetTabVisibility,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PermissionSetUserPermission {
    #[serde(default)]
    pub enabled: bool,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct Profile {
    #[serde(rename = "agentAccesses", default)]
    pub agent_accesses: Vec<ProfileAgentAccess>,
    #[serde(rename = "applicationVisibilities", default)]
    pub application_visibilities: Vec<ProfileApplicationVisibility>,
    #[serde(rename = "categoryGroupVisibilities", default)]
    pub category_group_visibilities: Vec<ProfileCategoryGroupVisibility>,
    #[serde(rename = "classAccesses", default)]
    pub class_accesses: Vec<ProfileApexClassAccess>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub custom: Option<bool>,
    #[serde(rename = "customMetadataTypeAccesses", default)]
    pub custom_metadata_type_accesses: Vec<ProfileCustomMetadataTypeAccess>,
    #[serde(rename = "customPermissions", default)]
    pub custom_permissions: Vec<ProfileCustomPermissions>,
    #[serde(rename = "customSettingAccesses", default)]
    pub custom_setting_accesses: Vec<ProfileCustomSettingAccess>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "externalDataSourceAccesses", default)]
    pub external_data_source_accesses: Vec<ProfileExternalDataSourceAccess>,
    #[serde(rename = "fieldPermissions", default)]
    pub field_permissions: Vec<ProfileFieldLevelSecurity>,
    #[serde(rename = "flowAccesses", default)]
    pub flow_accesses: Vec<ProfileFlowAccess>,
    #[serde(rename = "genComputingSummaryDefAccesses", default)]
    pub gen_computing_summary_def_accesses: Vec<ProfileGenComputingSummaryDefAccess>,
    #[serde(rename = "layoutAssignments", default)]
    pub layout_assignments: Vec<ProfileLayoutAssignment>,
    #[serde(rename = "loginFlows", default)]
    pub login_flows: Vec<serde_json::Value>,
    #[serde(
        rename = "loginHours",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub login_hours: Option<ProfileLoginHours>,
    #[serde(rename = "loginIpRanges", default)]
    pub login_ip_ranges: Vec<ProfileLoginIpRange>,
    #[serde(rename = "objectPermissions", default)]
    pub object_permissions: Vec<ProfileObjectPermissions>,
    #[serde(rename = "pageAccesses", default)]
    pub page_accesses: Vec<ProfileApexPageAccess>,
    #[serde(rename = "profileActionOverrides", default)]
    pub profile_action_overrides: Vec<ProfileActionOverride>,
    #[serde(rename = "recordTypeVisibilities", default)]
    pub record_type_visibilities: Vec<ProfileRecordTypeVisibility>,
    #[serde(rename = "servicePresenceStatusAccesses", default)]
    pub service_presence_status_accesses: Vec<ProfileServicePresenceStatusAccess>,
    #[serde(rename = "tabVisibilities", default)]
    pub tab_visibilities: Vec<ProfileTabVisibility>,
    #[serde(
        rename = "userLicense",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub user_license: Option<String>,
    #[serde(rename = "userPermissions", default)]
    pub user_permissions: Vec<ProfileUserPermission>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfileActionOverride {
    #[serde(rename = "actionName", default)]
    pub action_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(rename = "formFactor", default)]
    pub form_factor: serde_json::Value,
    #[serde(rename = "pageOrSobjectType", default)]
    pub page_or_sobject_type: String,
    #[serde(
        rename = "recordType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub record_type: Option<String>,
    #[serde(rename = "type", default)]
    pub r#type: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfileAgentAccess {
    #[serde(rename = "agentName", default)]
    pub agent_name: String,
    #[serde(default)]
    pub enabled: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfileApexClassAccess {
    #[serde(rename = "apexClass", default)]
    pub apex_class: String,
    #[serde(default)]
    pub enabled: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfileApexPageAccess {
    #[serde(rename = "apexPage", default)]
    pub apex_page: String,
    #[serde(default)]
    pub enabled: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfileApiOptions {
    #[serde(default)]
    pub project: serde_json::Value,
    #[serde(rename = "includeUserLicenses", default)]
    pub include_user_licenses: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfileApplicationVisibility {
    #[serde(default)]
    pub application: String,
    #[serde(default)]
    pub default: bool,
    #[serde(default)]
    pub visible: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfileCategoryGroupVisibility {
    #[serde(rename = "dataCategories", default)]
    pub data_categories: Vec<String>,
    #[serde(rename = "dataCategoryGroup", default)]
    pub data_category_group: String,
    #[serde(default)]
    pub visibility: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfileCustomMetadataTypeAccess {
    #[serde(default)]
    pub enabled: bool,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfileCustomPermissions {
    #[serde(default)]
    pub enabled: bool,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfileCustomSettingAccess {
    #[serde(default)]
    pub enabled: bool,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfileExternalDataSourceAccess {
    #[serde(default)]
    pub enabled: bool,
    #[serde(rename = "externalDataSource", default)]
    pub external_data_source: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfileFieldLevelSecurity {
    #[serde(default)]
    pub editable: bool,
    #[serde(default)]
    pub field: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub readable: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfileFlowAccess {
    #[serde(default)]
    pub enabled: bool,
    #[serde(default)]
    pub flow: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfileGenComputingSummaryDefAccess {
    #[serde(rename = "configName", default)]
    pub config_name: String,
    #[serde(default)]
    pub enabled: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfileLayoutAssignment {
    #[serde(default)]
    pub layout: String,
    #[serde(
        rename = "recordType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub record_type: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfileLoginHours {
    #[serde(rename = "fridayEnd", default, skip_serializing_if = "Option::is_none")]
    pub friday_end: Option<String>,
    #[serde(
        rename = "fridayStart",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub friday_start: Option<String>,
    #[serde(rename = "mondayEnd", default, skip_serializing_if = "Option::is_none")]
    pub monday_end: Option<String>,
    #[serde(
        rename = "mondayStart",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub monday_start: Option<String>,
    #[serde(
        rename = "saturdayEnd",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub saturday_end: Option<String>,
    #[serde(
        rename = "saturdayStart",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub saturday_start: Option<String>,
    #[serde(rename = "sundayEnd", default, skip_serializing_if = "Option::is_none")]
    pub sunday_end: Option<String>,
    #[serde(
        rename = "sundayStart",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub sunday_start: Option<String>,
    #[serde(
        rename = "thursdayEnd",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub thursday_end: Option<String>,
    #[serde(
        rename = "thursdayStart",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub thursday_start: Option<String>,
    #[serde(
        rename = "tuesdayEnd",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub tuesday_end: Option<String>,
    #[serde(
        rename = "tuesdayStart",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub tuesday_start: Option<String>,
    #[serde(
        rename = "wednesdayEnd",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub wednesday_end: Option<String>,
    #[serde(
        rename = "wednesdayStart",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub wednesday_start: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfileLoginIpRange {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "endAddress", default)]
    pub end_address: String,
    #[serde(rename = "startAddress", default)]
    pub start_address: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfileObjectPermissions {
    #[serde(
        rename = "allowCreate",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub allow_create: Option<bool>,
    #[serde(
        rename = "allowDelete",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub allow_delete: Option<bool>,
    #[serde(rename = "allowEdit", default, skip_serializing_if = "Option::is_none")]
    pub allow_edit: Option<bool>,
    #[serde(rename = "allowRead", default, skip_serializing_if = "Option::is_none")]
    pub allow_read: Option<bool>,
    #[serde(
        rename = "modifyAllRecords",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub modify_all_records: Option<bool>,
    #[serde(default)]
    pub object: String,
    #[serde(
        rename = "viewAllFields",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub view_all_fields: Option<bool>,
    #[serde(
        rename = "viewAllRecords",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub view_all_records: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfilePasswordPolicy {
    #[serde(
        rename = "forgotPasswordRedirect",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub forgot_password_redirect: Option<bool>,
    #[serde(rename = "lockoutInterval", default)]
    pub lockout_interval: f64,
    #[serde(rename = "maxLoginAttempts", default)]
    pub max_login_attempts: f64,
    #[serde(rename = "minimumPasswordLength", default)]
    pub minimum_password_length: f64,
    #[serde(
        rename = "minimumPasswordLifetime",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub minimum_password_lifetime: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub obscure: Option<bool>,
    #[serde(rename = "passwordComplexity", default)]
    pub password_complexity: f64,
    #[serde(rename = "passwordExpiration", default)]
    pub password_expiration: f64,
    #[serde(rename = "passwordHistory", default)]
    pub password_history: f64,
    #[serde(rename = "passwordQuestion", default)]
    pub password_question: f64,
    #[serde(default)]
    pub profile: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfileRecordTypeVisibility {
    #[serde(default)]
    pub default: bool,
    #[serde(
        rename = "personAccountDefault",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub person_account_default: Option<bool>,
    #[serde(rename = "recordType", default)]
    pub record_type: String,
    #[serde(default)]
    pub visible: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfileSearchLayouts {
    #[serde(default)]
    pub fields: Vec<String>,
    #[serde(
        rename = "profileName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub profile_name: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfileServicePresenceStatusAccess {
    #[serde(default)]
    pub enabled: bool,
    #[serde(rename = "servicePresenceStatus", default)]
    pub service_presence_status: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfileSessionSetting {
    #[serde(rename = "externalCommunityUserIdentityVerif", default)]
    pub external_community_user_identity_verif: bool,
    #[serde(rename = "forceLogout", default)]
    pub force_logout: bool,
    #[serde(default)]
    pub profile: String,
    #[serde(
        rename = "requiredSessionLevel",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub required_session_level: Option<serde_json::Value>,
    #[serde(rename = "sessionPersistence", default)]
    pub session_persistence: bool,
    #[serde(rename = "sessionTimeout", default)]
    pub session_timeout: f64,
    #[serde(rename = "sessionTimeoutWarning", default)]
    pub session_timeout_warning: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfileTabVisibility {
    #[serde(default)]
    pub tab: String,
    #[serde(default)]
    pub visibility: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ProfileUserPermission {
    #[serde(default)]
    pub enabled: bool,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct SharingBaseRule {
    #[serde(rename = "accessLevel", default)]
    pub access_level: String,
    #[serde(
        rename = "accountSettings",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub account_settings: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default)]
    pub label: String,
    #[serde(rename = "sharedTo", default)]
    pub shared_to: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct SharingCriteriaRule {
    #[serde(
        rename = "booleanFilter",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub boolean_filter: Option<String>,
    #[serde(rename = "criteriaItems", default)]
    pub criteria_items: Vec<serde_json::Value>,
    #[serde(rename = "includeRecordsOwnedByAll", default)]
    pub include_records_owned_by_all: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct SharingGuestRule {
    #[serde(
        rename = "booleanFilter",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub boolean_filter: Option<String>,
    #[serde(rename = "criteriaItems", default)]
    pub criteria_items: Vec<serde_json::Value>,
    #[serde(rename = "includeHVUOwnedRecords", default)]
    pub include_hvu_owned_records: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct SharingOwnerRule {
    #[serde(rename = "sharedFrom", default)]
    pub shared_from: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct SharingReasonTranslation {
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct SharingRecalculation {
    #[serde(rename = "className", default)]
    pub class_name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct SharingRules {
    #[serde(rename = "sharingCriteriaRules", default)]
    pub sharing_criteria_rules: Vec<SharingCriteriaRule>,
    #[serde(rename = "sharingGuestRules", default)]
    pub sharing_guest_rules: Vec<SharingGuestRule>,
    #[serde(rename = "sharingOwnerRules", default)]
    pub sharing_owner_rules: Vec<SharingOwnerRule>,
    #[serde(rename = "sharingTerritoryRules", default)]
    pub sharing_territory_rules: Vec<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct SharingSet {
    #[serde(rename = "accessMappings", default)]
    pub access_mappings: Vec<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub profiles: Vec<String>,
}
