#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: <https://github.com/forcedotcom/wsdl>
//!
//! DO NOT EDIT - This file is automatically generated

//! Picklist Values, Picklist Translations

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PicklistEntry {
    #[serde(default)]
    pub active: bool,
    #[serde(rename = "defaultValue", default)]
    pub default_value: bool,
    #[serde(default)]
    pub label: String,
    #[serde(rename = "validFor", default, skip_serializing_if = "Option::is_none")]
    pub valid_for: Option<String>,
    #[serde(default)]
    pub value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PicklistValue {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    #[serde(default)]
    pub default: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "isActive", default, skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(
        rename = "allowEmail",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub allow_email: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub closed: Option<bool>,
    #[serde(rename = "controllingFieldValues", default)]
    pub controlling_field_values: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub converted: Option<bool>,
    #[serde(
        rename = "cssExposed",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub css_exposed: Option<bool>,
    #[serde(
        rename = "forecastCategory",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub forecast_category: Option<serde_json::Value>,
    #[serde(
        rename = "highPriority",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub high_priority: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub probability: Option<f64>,
    #[serde(
        rename = "reverseRole",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub reverse_role: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reviewed: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub won: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct PicklistValueTranslation {
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub translation: Option<String>,
}
