#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: <https://github.com/forcedotcom/wsdl>
//!
//! DO NOT EDIT - This file is automatically generated

//! Quick Actions, Global Actions, Action Links

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum ActionLinkExecutionsAllowed {
    #[default]
    Once,
    OncePerUser,
    Unlimited,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum ActionLinkHttpMethod {
    #[default]
    HttpDelete,
    HttpHead,
    HttpGet,
    HttpPatch,
    HttpPost,
    HttpPut,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum ActionLinkType {
    #[default]
    API,
    APIAsync,
    Download,
    UI,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum ActionLinkUserVisibility {
    #[default]
    Creator,
    Everyone,
    EveryoneButCreator,
    Manager,
    CustomUser,
    CustomExcludedUser,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum QuickActionLabel {
    #[default]
    LogACall,
    LogANote,
    New,
    NewRecordType,
    Update,
    NewChild,
    NewChildRecordType,
    CreateNew,
    CreateNewRecordType,
    SendEmail,
    QuickRecordType,
    Quick,
    EditDescription,
    Defer,
    ChangeDueDate,
    ChangePriority,
    ChangeStatus,
    SocialPost,
    Escalate,
    EscalateToRecord,
    OfferFeedback,
    RequestFeedback,
    AddRecord,
    AddMember,
    Reply,
    ReplyAll,
    Forward,
    ScheduleAppointment,
    EnrollInProgram,
    ModifyAppointment,
    PatientDetails,
    AcceptBroadcast,
    SelectCoverage,
    SummarizeCase,
    AssetHierarchy,
    PartReturnRequest,
    PerformCount,
    ViewCoverage,
    Quip,
    SendConversationMessage,
    NewQuote,
    LaunchDataCapture,
    RelocateAsset,
    ReplaceAsset,
    CloseCase,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum QuickActionType {
    #[default]
    Create,
    VisualforcePage,
    Post,
    SendEmail,
    LogACall,
    SocialPost,
    Canvas,
    Update,
    LightningComponent,
    LightningWebComponent,
    Flow,
    MobileExtension,
    Quip,
    SendConversationMessage,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ActionLauncherItemDef {
    #[serde(default)]
    pub identifier: String,
    #[serde(rename = "itemActionType", default)]
    pub item_action_type: serde_json::Value,
    #[serde(rename = "itemCategory", default)]
    pub item_category: serde_json::Value,
    #[serde(rename = "itemLanguage", default)]
    pub item_language: String,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(rename = "subType", default)]
    pub sub_type: String,
    #[serde(rename = "type", default)]
    pub r#type: String,
    #[serde(
        rename = "versionNumber",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub version_number: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ActionLinkGroupTemplate {
    #[serde(rename = "actionLinkTemplates", default)]
    pub action_link_templates: Vec<ActionLinkTemplate>,
    #[serde(default)]
    pub category: serde_json::Value,
    #[serde(rename = "executionsAllowed", default)]
    pub executions_allowed: ActionLinkExecutionsAllowed,
    #[serde(
        rename = "hoursUntilExpiration",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub hours_until_expiration: Option<f64>,
    #[serde(rename = "isPublished", default)]
    pub is_published: bool,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ActionLinkTemplate {
    #[serde(rename = "actionUrl", default)]
    pub action_url: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub headers: Option<String>,
    #[serde(rename = "isConfirmationRequired", default)]
    pub is_confirmation_required: bool,
    #[serde(rename = "isGroupDefault", default)]
    pub is_group_default: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "labelKey", default)]
    pub label_key: String,
    #[serde(rename = "linkType", default)]
    pub link_type: ActionLinkType,
    #[serde(default)]
    pub method: ActionLinkHttpMethod,
    #[serde(default)]
    pub position: f64,
    #[serde(
        rename = "requestBody",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub request_body: Option<String>,
    #[serde(rename = "userAlias", default, skip_serializing_if = "Option::is_none")]
    pub user_alias: Option<String>,
    #[serde(rename = "userVisibility", default)]
    pub user_visibility: ActionLinkUserVisibility,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ActionPlanTemplate {
    #[serde(rename = "actionPlanTemplateItem", default)]
    pub action_plan_template_item: Vec<ActionPlanTemplateItem>,
    #[serde(rename = "actionPlanTemplateItemDependencies", default)]
    pub action_plan_template_item_dependencies: Vec<ActionPlanTemplateItemDependency>,
    #[serde(
        rename = "actionPlanType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub action_plan_type: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(
        rename = "estimatedCompletionDays",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub estimated_completion_days: Option<f64>,
    #[serde(
        rename = "fileBasedTemplatePath",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub file_based_template_path: Option<String>,
    #[serde(rename = "isAdHocItemCreationEnabled", default)]
    pub is_ad_hoc_item_creation_enabled: bool,
    #[serde(default)]
    pub name: String,
    #[serde(
        rename = "sourceType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub source_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subcategory: Option<String>,
    #[serde(rename = "targetEntityType", default)]
    pub target_entity_type: String,
    #[serde(rename = "uniqueName", default)]
    pub unique_name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ActionPlanTemplateItem {
    #[serde(rename = "actionPlanTemplateItemValue", default)]
    pub action_plan_template_item_value: Vec<ActionPlanTemplateItemValue>,
    #[serde(
        rename = "displayOrder",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub display_order: Option<f64>,
    #[serde(
        rename = "isRequired",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_required: Option<bool>,
    #[serde(rename = "itemEntityType", default)]
    pub item_entity_type: String,
    #[serde(default)]
    pub name: String,
    #[serde(rename = "uniqueName", default)]
    pub unique_name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ActionPlanTemplateItemDependency {
    #[serde(rename = "creationType", default)]
    pub creation_type: String,
    #[serde(default)]
    pub name: String,
    #[serde(rename = "previousTemplateItem", default)]
    pub previous_template_item: ActionPlanTemplateItem,
    #[serde(rename = "templateItem", default)]
    pub template_item: ActionPlanTemplateItem,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ActionPlanTemplateItemValue {
    #[serde(rename = "itemEntityType", default)]
    pub item_entity_type: String,
    #[serde(default)]
    pub name: String,
    #[serde(
        rename = "valueFormula",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub value_formula: Option<String>,
    #[serde(
        rename = "valueLiteral",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub value_literal: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct GlobalQuickActionTranslation {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub aspect: Option<String>,
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct QuickAction {
    #[serde(
        rename = "actionSubtype",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub action_subtype: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub canvas: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "fieldOverrides", default)]
    pub field_overrides: Vec<serde_json::Value>,
    #[serde(
        rename = "flowDefinition",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub flow_definition: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub height: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[serde(
        rename = "isProtected",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_protected: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(
        rename = "lightningComponent",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub lightning_component: Option<String>,
    #[serde(
        rename = "lightningWebComponent",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub lightning_web_component: Option<String>,
    #[serde(rename = "optionsCreateFeedItem", default)]
    pub options_create_feed_item: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub page: Option<String>,
    #[serde(
        rename = "quickActionLayout",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub quick_action_layout: Option<QuickActionLayout>,
    #[serde(
        rename = "quickActionSendEmailOptions",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub quick_action_send_email_options: Option<QuickActionSendEmailOptions>,
    #[serde(
        rename = "standardLabel",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub standard_label: Option<QuickActionLabel>,
    #[serde(
        rename = "successMessage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub success_message: Option<String>,
    #[serde(
        rename = "targetObject",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub target_object: Option<String>,
    #[serde(
        rename = "targetParentField",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub target_parent_field: Option<String>,
    #[serde(
        rename = "targetRecordType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub target_record_type: Option<String>,
    #[serde(rename = "type", default)]
    pub r#type: QuickActionType,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub width: Option<f64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct QuickActionLayout {
    #[serde(rename = "layoutSectionStyle", default)]
    pub layout_section_style: serde_json::Value,
    #[serde(rename = "quickActionLayoutColumns", default)]
    pub quick_action_layout_columns: Vec<QuickActionLayoutColumn>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct QuickActionLayoutColumn {
    #[serde(rename = "quickActionLayoutItems", default)]
    pub quick_action_layout_items: Vec<QuickActionLayoutItem>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct QuickActionLayoutItem {
    #[serde(
        rename = "emptySpace",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub empty_space: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub field: Option<String>,
    #[serde(
        rename = "uiBehavior",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub ui_behavior: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct QuickActionSendEmailOptions {
    #[serde(
        rename = "defaultEmailTemplateName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub default_email_template_name: Option<String>,
    #[serde(rename = "ignoreDefaultEmailTemplateSubject", default)]
    pub ignore_default_email_template_subject: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct QuickActionTranslation {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub aspect: Option<String>,
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub name: String,
}
