#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: https://github.com/forcedotcom/wsdl
//!
//! DO NOT EDIT - This file is automatically generated

//! Reports, dashboards, and analytics

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DashboardFilterOperation {
    #[default]
    equals,
    notEqual,
    lessThan,
    greaterThan,
    lessOrEqual,
    greaterOrEqual,
    contains,
    notContain,
    startsWith,
    includes,
    excludes,
    between,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum ReportStatus {
    #[default]
    NEW,
    TRAINING,
    COMPLETED,
    ERROR,
    NOT_ENOUGH_DATA_AFTER_PARSING,
    NOT_ENOUGH_DATA_WITH_CONTACT_REASON,
    LOW_CLUSTER_QUALITY,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum ReportTypeCategory {
    #[default]
    accounts,
    opportunities,
    forecasts,
    cases,
    leads,
    campaigns,
    activities,
    busop,
    products,
    admin,
    territory,
    other,
    content,
    usage_entitlement,
    wdc,
    calibration,
    territory2,
    quotes,
    individual,
    employee,
    data_cloud,
    commerce,
    flow,
    semantic_model,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum ReportAggrType {
    #[default]
    Sum,
    Average,
    Maximum,
    Minimum,
    Unique,
    RowCount,
    Median,
    Noop,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum ReportAggregateDatatype {
    #[default]
    currency,
    percent,
    number,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum ReportChartComponentSize {
    #[default]
    SMALL,
    MEDIUM,
    LARGE,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum ReportFormat {
    #[default]
    MultiBlock,
    Matrix,
    Summary,
    Tabular,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum ReportSortType {
    #[default]
    Column,
    Aggregate,
    CustomSummaryFormula,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum ReportChartSize {
    #[default]
    Tiny,
    Small,
    Medium,
    Large,
    Huge,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum ReportBucketFieldType {
    #[default]
    text,
    number,
    picklist,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DashboardComponentColumnType {
    #[default]
    aggregate,
    detail,
    grouping,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum ReportSummaryType {
    #[default]
    Sum,
    Average,
    Maximum,
    Minimum,
    Unique,
    Median,
    Noop,
    None,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DashboardComponentType {
    #[default]
    Bar,
    BarGrouped,
    BarStacked,
    BarStacked100,
    Column,
    ColumnGrouped,
    ColumnStacked,
    ColumnStacked100,
    Line,
    LineGrouped,
    Pie,
    Table,
    Metric,
    Gauge,
    LineCumulative,
    LineGroupedCumulative,
    Scontrol,
    VisualforcePage,
    Donut,
    Funnel,
    ColumnLine,
    ColumnLineGrouped,
    ColumnLineStacked,
    ColumnLineStacked100,
    Scatter,
    ScatterGrouped,
    FlexTable,
    Image,
    RichText,
    PulseMetric,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DashboardComponentSize {
    #[default]
    Narrow,
    Medium,
    Wide,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DashboardComponentFilter {
    #[default]
    RowLabelAscending,
    RowLabelDescending,
    RowValueAscending,
    RowValueDescending,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum ReportFormulaNullTreatment {
    #[default]
    n,
    z,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum ReportJobSourceTypes {
    #[default]
    tabular,
    summary,
    snapshot,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DashboardType {
    #[default]
    SpecifiedUser,
    LoggedInUser,
    MyTeamUser,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportBucketField {
    #[serde(rename = "bucketType", default)]
    pub bucket_type: ReportBucketFieldType,
    #[serde(rename = "developerName", default)]
    pub developer_name: String,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(rename = "nullTreatment", default)]
    pub null_treatment: ReportFormulaNullTreatment,
    #[serde(rename = "otherBucketLabel", default)]
    pub other_bucket_label: String,
    #[serde(rename = "sourceColumnName", default)]
    pub source_column_name: String,
    #[serde(rename = "useOther", default)]
    pub use_other: bool,
    #[serde(default)]
    pub values: Vec<ReportBucketFieldValue>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct Dashboard {
    #[serde(rename = "backgroundEndColor", default)]
    pub background_end_color: String,
    #[serde(rename = "backgroundFadeDirection", default)]
    pub background_fade_direction: serde_json::Value,
    #[serde(rename = "backgroundStartColor", default)]
    pub background_start_color: String,
    #[serde(rename = "chartTheme", default)]
    pub chart_theme: serde_json::Value,
    #[serde(rename = "colorPalette", default)]
    pub color_palette: serde_json::Value,
    #[serde(rename = "dashboardChartTheme", default)]
    pub dashboard_chart_theme: serde_json::Value,
    #[serde(rename = "dashboardColorPalette", default)]
    pub dashboard_color_palette: serde_json::Value,
    #[serde(rename = "dashboardFilters", default)]
    pub dashboard_filters: Vec<DashboardFilter>,
    #[serde(rename = "dashboardGridLayout", default)]
    pub dashboard_grid_layout: DashboardGridLayout,
    #[serde(rename = "dashboardResultRefreshedDate", default)]
    pub dashboard_result_refreshed_date: String,
    #[serde(rename = "dashboardResultRunningUser", default)]
    pub dashboard_result_running_user: String,
    #[serde(rename = "dashboardType", default)]
    pub dashboard_type: DashboardType,
    #[serde(default)]
    pub description: String,
    #[serde(rename = "folderName", default)]
    pub folder_name: String,
    #[serde(rename = "isGridLayout", default)]
    pub is_grid_layout: bool,
    #[serde(rename = "leftSection", default)]
    pub left_section: DashboardComponentSection,
    #[serde(rename = "middleSection", default)]
    pub middle_section: DashboardComponentSection,
    #[serde(rename = "numSubscriptions", default)]
    pub num_subscriptions: f64,
    #[serde(default)]
    pub owner: String,
    #[serde(rename = "rightSection", default)]
    pub right_section: DashboardComponentSection,
    #[serde(rename = "runningUser", default)]
    pub running_user: String,
    #[serde(rename = "textColor", default)]
    pub text_color: String,
    #[serde(default)]
    pub title: String,
    #[serde(rename = "titleColor", default)]
    pub title_color: String,
    #[serde(rename = "titleSize", default)]
    pub title_size: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportColumn {
    #[serde(rename = "aggregateTypes", default)]
    pub aggregate_types: Vec<ReportSummaryType>,
    #[serde(default)]
    pub field: String,
    #[serde(rename = "isExtendedColumn", default)]
    pub is_extended_column: bool,
    #[serde(rename = "reverseColors", default)]
    pub reverse_colors: bool,
    #[serde(rename = "showChanges", default)]
    pub show_changes: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportLayoutSection {
    #[serde(default)]
    pub columns: Vec<ReportTypeColumn>,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DashboardTableColumn {
    #[serde(rename = "aggregateType", default)]
    pub aggregate_type: ReportSummaryType,
    #[serde(rename = "calculatePercent", default)]
    pub calculate_percent: bool,
    #[serde(default)]
    pub column: String,
    #[serde(rename = "decimalPlaces", default)]
    pub decimal_places: f64,
    #[serde(rename = "showSubTotal", default)]
    pub show_sub_total: bool,
    #[serde(rename = "showTotal", default)]
    pub show_total: bool,
    #[serde(rename = "sortBy", default)]
    pub sort_by: DashboardComponentFilter,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct Report {
    #[serde(rename = "aggregateFilters", default)]
    pub aggregate_filters: Vec<ReportAggregateFilter>,
    #[serde(default)]
    pub aggregates: Vec<ReportAggregate>,
    #[serde(default)]
    pub block: Vec<Box<Report>>,
    #[serde(rename = "blockInfo", default)]
    pub block_info: ReportBlockInfo,
    #[serde(default)]
    pub buckets: Vec<ReportBucketField>,
    #[serde(default)]
    pub chart: ReportChart,
    #[serde(rename = "colorRanges", default)]
    pub color_ranges: Vec<ReportColorRange>,
    #[serde(default)]
    pub columns: Vec<ReportColumn>,
    #[serde(rename = "crossFilters", default)]
    pub cross_filters: Vec<ReportCrossFilter>,
    #[serde(default)]
    pub currency: serde_json::Value,
    #[serde(rename = "customDetailFormulas", default)]
    pub custom_detail_formulas: Vec<ReportCustomDetailFormula>,
    #[serde(rename = "dataCategoryFilters", default)]
    pub data_category_filters: Vec<ReportDataCategoryFilter>,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub division: String,
    #[serde(default)]
    pub filter: ReportFilter,
    #[serde(rename = "folderName", default)]
    pub folder_name: String,
    #[serde(default)]
    pub format: ReportFormat,
    #[serde(rename = "formattingRules", default)]
    pub formatting_rules: Vec<ReportFormattingRule>,
    #[serde(rename = "groupingsAcross", default)]
    pub groupings_across: Vec<ReportGrouping>,
    #[serde(rename = "groupingsDown", default)]
    pub groupings_down: Vec<ReportGrouping>,
    #[serde(rename = "historicalSelector", default)]
    pub historical_selector: ReportHistoricalSelector,
    #[serde(rename = "isSmartTotalDisabled", default)]
    pub is_smart_total_disabled: bool,
    #[serde(default)]
    pub name: String,
    #[serde(rename = "numSubscriptions", default)]
    pub num_subscriptions: f64,
    #[serde(default)]
    pub params: Vec<ReportParam>,
    #[serde(rename = "reportType", default)]
    pub report_type: String,
    #[serde(rename = "reportTypeApiName", default)]
    pub report_type_api_name: String,
    #[serde(rename = "roleHierarchyFilter", default)]
    pub role_hierarchy_filter: String,
    #[serde(rename = "rowLimit", default)]
    pub row_limit: f64,
    #[serde(default)]
    pub scope: String,
    #[serde(rename = "showCurrentDate", default)]
    pub show_current_date: bool,
    #[serde(rename = "showDetails", default)]
    pub show_details: bool,
    #[serde(rename = "showGrandTotal", default)]
    pub show_grand_total: bool,
    #[serde(rename = "showSubTotals", default)]
    pub show_sub_totals: bool,
    #[serde(rename = "sortColumn", default)]
    pub sort_column: String,
    #[serde(rename = "sortOrder", default)]
    pub sort_order: serde_json::Value,
    #[serde(rename = "territoryHierarchyFilter", default)]
    pub territory_hierarchy_filter: String,
    #[serde(rename = "timeFrameFilter", default)]
    pub time_frame_filter: ReportTimeFrameFilter,
    #[serde(rename = "userFilter", default)]
    pub user_filter: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DashboardComponentGroupingSortProperties {
    #[serde(rename = "groupingSorts", default)]
    pub grouping_sorts: Vec<DashboardComponentGroupingSort>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DashboardGridComponent {
    #[serde(rename = "colSpan", default)]
    pub col_span: f64,
    #[serde(rename = "columnIndex", default)]
    pub column_index: f64,
    #[serde(rename = "dashboardComponent", default)]
    pub dashboard_component: DashboardComponent,
    #[serde(rename = "rowIndex", default)]
    pub row_index: f64,
    #[serde(rename = "rowSpan", default)]
    pub row_span: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DashboardGridLayout {
    #[serde(rename = "dashboardGridComponents", default)]
    pub dashboard_grid_components: Vec<DashboardGridComponent>,
    #[serde(rename = "numberOfColumns", default)]
    pub number_of_columns: f64,
    #[serde(rename = "rowHeight", default)]
    pub row_height: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportFilterItem {
    #[serde(default)]
    pub column: String,
    #[serde(rename = "columnToColumn", default)]
    pub column_to_column: bool,
    #[serde(rename = "isUnlocked", default)]
    pub is_unlocked: bool,
    #[serde(default)]
    pub operator: serde_json::Value,
    #[serde(default)]
    pub snapshot: String,
    #[serde(default)]
    pub value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportFormattingRule {
    #[serde(default)]
    pub aggregate: ReportSummaryType,
    #[serde(rename = "columnName", default)]
    pub column_name: String,
    #[serde(default)]
    pub values: Vec<ReportFormattingRuleValue>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportGrouping {
    #[serde(rename = "aggregateType", default)]
    pub aggregate_type: ReportAggrType,
    #[serde(rename = "dateGranularity", default)]
    pub date_granularity: serde_json::Value,
    #[serde(default)]
    pub field: String,
    #[serde(rename = "sortByName", default)]
    pub sort_by_name: String,
    #[serde(rename = "sortOrder", default)]
    pub sort_order: serde_json::Value,
    #[serde(rename = "sortType", default)]
    pub sort_type: ReportSortType,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportType {
    #[serde(default)]
    pub autogenerated: bool,
    #[serde(rename = "baseObject", default)]
    pub base_object: String,
    #[serde(default)]
    pub category: ReportTypeCategory,
    #[serde(default)]
    pub deployed: bool,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub join: serde_json::Value,
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub sections: Vec<ReportLayoutSection>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportHistoricalSelector {
    #[serde(default)]
    pub snapshot: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportBucketFieldSourceValue {
    #[serde(default)]
    pub from: String,
    #[serde(rename = "sourceValue", default)]
    pub source_value: String,
    #[serde(default)]
    pub to: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportDataCategoryFilter {
    #[serde(rename = "dataCategory", default)]
    pub data_category: String,
    #[serde(rename = "dataCategoryGroup", default)]
    pub data_category_group: String,
    #[serde(default)]
    pub operator: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DashboardComponentContent {
    #[serde(rename = "additionalInfo", default)]
    pub additional_info: String,
    #[serde(rename = "altText", default)]
    pub alt_text: String,
    #[serde(rename = "fileName", default)]
    pub file_name: String,
    #[serde(default)]
    pub fit: serde_json::Value,
    #[serde(rename = "horizontalAlignment", default)]
    pub horizontal_alignment: serde_json::Value,
    #[serde(rename = "richTextContent", default)]
    pub rich_text_content: String,
    #[serde(default)]
    pub tooltip: String,
    #[serde(rename = "verticalAlignment", default)]
    pub vertical_alignment: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportFormattingRuleValue {
    #[serde(rename = "backgroundColor", default)]
    pub background_color: String,
    #[serde(rename = "rangeUpperBound", default)]
    pub range_upper_bound: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DashboardComponentSection {
    #[serde(rename = "columnSize", default)]
    pub column_size: DashboardComponentSize,
    #[serde(default)]
    pub components: Vec<DashboardComponent>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportTypeTranslation {
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub sections: Vec<ReportTypeSectionTranslation>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DashboardComponent {
    #[serde(rename = "autoselectColumnsFromReport", default)]
    pub autoselect_columns_from_report: bool,
    #[serde(rename = "chartAxisRange", default)]
    pub chart_axis_range: serde_json::Value,
    #[serde(rename = "chartAxisRangeMax", default)]
    pub chart_axis_range_max: f64,
    #[serde(rename = "chartAxisRangeMin", default)]
    pub chart_axis_range_min: f64,
    #[serde(rename = "chartSummary", default)]
    pub chart_summary: Vec<serde_json::Value>,
    #[serde(rename = "componentChartTheme", default)]
    pub component_chart_theme: serde_json::Value,
    #[serde(rename = "componentType", default)]
    pub component_type: DashboardComponentType,
    #[serde(rename = "dashboardComponentContents", default)]
    pub dashboard_component_contents: Vec<DashboardComponentContent>,
    #[serde(rename = "dashboardDynamicValues", default)]
    pub dashboard_dynamic_values: Vec<DashboardDynamicValue>,
    #[serde(rename = "dashboardFilterColumns", default)]
    pub dashboard_filter_columns: Vec<DashboardFilterColumn>,
    #[serde(rename = "dashboardTableColumn", default)]
    pub dashboard_table_column: Vec<DashboardTableColumn>,
    #[serde(rename = "decimalPrecision", default)]
    pub decimal_precision: f64,
    #[serde(rename = "displayUnits", default)]
    pub display_units: serde_json::Value,
    #[serde(rename = "drillDownUrl", default)]
    pub drill_down_url: String,
    #[serde(rename = "drillEnabled", default)]
    pub drill_enabled: bool,
    #[serde(rename = "drillToDetailEnabled", default)]
    pub drill_to_detail_enabled: bool,
    #[serde(rename = "enableHover", default)]
    pub enable_hover: bool,
    #[serde(rename = "expandOthers", default)]
    pub expand_others: bool,
    #[serde(rename = "flexComponentProperties", default)]
    pub flex_component_properties: DashboardFlexTableComponentProperties,
    #[serde(default)]
    pub footer: String,
    #[serde(rename = "gaugeMax", default)]
    pub gauge_max: f64,
    #[serde(rename = "gaugeMin", default)]
    pub gauge_min: f64,
    #[serde(rename = "groupingColumn", default)]
    pub grouping_column: Vec<String>,
    #[serde(rename = "groupingSortProperties", default)]
    pub grouping_sort_properties: DashboardComponentGroupingSortProperties,
    #[serde(default)]
    pub header: String,
    #[serde(rename = "indicatorBreakpoint1", default)]
    pub indicator_breakpoint_1: f64,
    #[serde(rename = "indicatorBreakpoint2", default)]
    pub indicator_breakpoint_2: f64,
    #[serde(rename = "indicatorHighColor", default)]
    pub indicator_high_color: String,
    #[serde(rename = "indicatorLowColor", default)]
    pub indicator_low_color: String,
    #[serde(rename = "indicatorMiddleColor", default)]
    pub indicator_middle_color: String,
    #[serde(rename = "legendPosition", default)]
    pub legend_position: serde_json::Value,
    #[serde(rename = "maxValuesDisplayed", default)]
    pub max_values_displayed: f64,
    #[serde(rename = "metricLabel", default)]
    pub metric_label: String,
    #[serde(default)]
    pub page: String,
    #[serde(rename = "pageHeightInPixels", default)]
    pub page_height_in_pixels: f64,
    #[serde(default)]
    pub report: String,
    #[serde(default)]
    pub scontrol: String,
    #[serde(rename = "scontrolHeightInPixels", default)]
    pub scontrol_height_in_pixels: f64,
    #[serde(rename = "showPercentage", default)]
    pub show_percentage: bool,
    #[serde(rename = "showPicturesOnCharts", default)]
    pub show_pictures_on_charts: bool,
    #[serde(rename = "showPicturesOnTables", default)]
    pub show_pictures_on_tables: bool,
    #[serde(rename = "showRange", default)]
    pub show_range: bool,
    #[serde(rename = "showTotal", default)]
    pub show_total: bool,
    #[serde(rename = "showValues", default)]
    pub show_values: bool,
    #[serde(rename = "sortBy", default)]
    pub sort_by: DashboardComponentFilter,
    #[serde(rename = "sortLegendValues", default)]
    pub sort_legend_values: bool,
    #[serde(default)]
    pub title: String,
    #[serde(rename = "useReportChart", default)]
    pub use_report_chart: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DashboardComponentSortInfo {
    #[serde(rename = "sortColumn", default)]
    pub sort_column: String,
    #[serde(rename = "sortOrder", default)]
    pub sort_order: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportTimeFrameFilter {
    #[serde(rename = "dateColumn", default)]
    pub date_column: String,
    #[serde(rename = "endDate", default)]
    pub end_date: String,
    #[serde(default)]
    pub interval: serde_json::Value,
    #[serde(rename = "startDate", default)]
    pub start_date: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportChartComponentLayoutItem {
    #[serde(rename = "cacheData", default)]
    pub cache_data: bool,
    #[serde(rename = "contextFilterableField", default)]
    pub context_filterable_field: String,
    #[serde(default)]
    pub error: String,
    #[serde(rename = "hideOnError", default)]
    pub hide_on_error: bool,
    #[serde(rename = "includeContext", default)]
    pub include_context: bool,
    #[serde(rename = "reportName", default)]
    pub report_name: String,
    #[serde(rename = "showTitle", default)]
    pub show_title: bool,
    #[serde(default)]
    pub size: ReportChartComponentSize,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DashboardDynamicValue {
    #[serde(rename = "additionalInfo", default)]
    pub additional_info: String,
    #[serde(rename = "fieldName", default)]
    pub field_name: String,
    #[serde(rename = "isDynamicUser", default)]
    pub is_dynamic_user: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DashboardComponentGroupingSort {
    #[serde(rename = "groupingLevel", default)]
    pub grouping_level: String,
    #[serde(rename = "inheritedReportGroupingSort", default)]
    pub inherited_report_grouping_sort: String,
    #[serde(rename = "sortColumn", default)]
    pub sort_column: String,
    #[serde(rename = "sortOrder", default)]
    pub sort_order: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportTypeSectionTranslation {
    #[serde(default)]
    pub columns: Vec<ReportTypeColumnTranslation>,
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DashboardFilter {
    #[serde(rename = "dashboardFilterOptions", default)]
    pub dashboard_filter_options: Vec<DashboardFilterOption>,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportCrossFilter {
    #[serde(rename = "criteriaItems", default)]
    pub criteria_items: Vec<ReportFilterItem>,
    #[serde(default)]
    pub operation: serde_json::Value,
    #[serde(rename = "primaryTableColumn", default)]
    pub primary_table_column: String,
    #[serde(rename = "relatedTable", default)]
    pub related_table: String,
    #[serde(rename = "relatedTableJoinColumn", default)]
    pub related_table_join_column: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportTypeColumn {
    #[serde(rename = "checkedByDefault", default)]
    pub checked_by_default: bool,
    #[serde(rename = "displayNameOverride", default)]
    pub display_name_override: String,
    #[serde(default)]
    pub field: String,
    #[serde(default)]
    pub table: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportCustomDetailFormula {
    #[serde(rename = "calculatedFormula", default)]
    pub calculated_formula: String,
    #[serde(rename = "dataType", default)]
    pub data_type: String,
    #[serde(default)]
    pub description: String,
    #[serde(rename = "developerName", default)]
    pub developer_name: String,
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub scale: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportChart {
    #[serde(rename = "backgroundColor1", default)]
    pub background_color_1: String,
    #[serde(rename = "backgroundColor2", default)]
    pub background_color_2: String,
    #[serde(rename = "backgroundFadeDir", default)]
    pub background_fade_dir: serde_json::Value,
    #[serde(rename = "chartSummaries", default)]
    pub chart_summaries: Vec<serde_json::Value>,
    #[serde(rename = "chartType", default)]
    pub chart_type: serde_json::Value,
    #[serde(rename = "enableHoverLabels", default)]
    pub enable_hover_labels: bool,
    #[serde(rename = "expandOthers", default)]
    pub expand_others: bool,
    #[serde(rename = "groupingColumn", default)]
    pub grouping_column: String,
    #[serde(rename = "legendPosition", default)]
    pub legend_position: serde_json::Value,
    #[serde(default)]
    pub location: serde_json::Value,
    #[serde(rename = "secondaryGroupingColumn", default)]
    pub secondary_grouping_column: String,
    #[serde(rename = "showAxisLabels", default)]
    pub show_axis_labels: bool,
    #[serde(rename = "showPercentage", default)]
    pub show_percentage: bool,
    #[serde(rename = "showTotal", default)]
    pub show_total: bool,
    #[serde(rename = "showValues", default)]
    pub show_values: bool,
    #[serde(default)]
    pub size: ReportChartSize,
    #[serde(rename = "summaryAxisManualRangeEnd", default)]
    pub summary_axis_manual_range_end: f64,
    #[serde(rename = "summaryAxisManualRangeStart", default)]
    pub summary_axis_manual_range_start: f64,
    #[serde(rename = "summaryAxisRange", default)]
    pub summary_axis_range: serde_json::Value,
    #[serde(rename = "textColor", default)]
    pub text_color: String,
    #[serde(rename = "textSize", default)]
    pub text_size: f64,
    #[serde(default)]
    pub title: String,
    #[serde(rename = "titleColor", default)]
    pub title_color: String,
    #[serde(rename = "titleSize", default)]
    pub title_size: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DashboardFlexTableComponentProperties {
    #[serde(rename = "decimalPrecision", default)]
    pub decimal_precision: f64,
    #[serde(rename = "flexTableColumn", default)]
    pub flex_table_column: Vec<DashboardComponentColumn>,
    #[serde(rename = "flexTableSortInfo", default)]
    pub flex_table_sort_info: DashboardComponentSortInfo,
    #[serde(rename = "hideChatterPhotos", default)]
    pub hide_chatter_photos: bool,
    #[serde(rename = "useReportTableSetting", default)]
    pub use_report_table_setting: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportAggregateReference {
    #[serde(default)]
    pub aggregate: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportColorRange {
    #[serde(default)]
    pub aggregate: ReportSummaryType,
    #[serde(rename = "columnName", default)]
    pub column_name: String,
    #[serde(rename = "highBreakpoint", default)]
    pub high_breakpoint: f64,
    #[serde(rename = "highColor", default)]
    pub high_color: String,
    #[serde(rename = "lowBreakpoint", default)]
    pub low_breakpoint: f64,
    #[serde(rename = "lowColor", default)]
    pub low_color: String,
    #[serde(rename = "midColor", default)]
    pub mid_color: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportFilter {
    #[serde(rename = "booleanFilter", default)]
    pub boolean_filter: String,
    #[serde(rename = "criteriaItems", default)]
    pub criteria_items: Vec<ReportFilterItem>,
    #[serde(default)]
    pub language: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportParam {
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportTypeColumnTranslation {
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportAggregateFilter {
    #[serde(default)]
    pub aggregate: String,
    #[serde(default)]
    pub operator: String,
    #[serde(default)]
    pub value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportAggregate {
    #[serde(rename = "acrossGroupingContext", default)]
    pub across_grouping_context: String,
    #[serde(rename = "calculatedFormula", default)]
    pub calculated_formula: String,
    #[serde(default)]
    pub datatype: ReportAggregateDatatype,
    #[serde(default)]
    pub description: String,
    #[serde(rename = "developerName", default)]
    pub developer_name: String,
    #[serde(rename = "downGroupingContext", default)]
    pub down_grouping_context: String,
    #[serde(rename = "isActive", default)]
    pub is_active: bool,
    #[serde(rename = "isCrossBlock", default)]
    pub is_cross_block: bool,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(rename = "reportType", default)]
    pub report_type: String,
    #[serde(default)]
    pub scale: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportBlockInfo {
    #[serde(rename = "aggregateReferences", default)]
    pub aggregate_references: Vec<ReportAggregateReference>,
    #[serde(rename = "blockId", default)]
    pub block_id: String,
    #[serde(rename = "joinTable", default)]
    pub join_table: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DashboardFilterOption {
    #[serde(default)]
    pub operator: DashboardFilterOperation,
    #[serde(default)]
    pub values: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DashboardFilterColumn {
    #[serde(default)]
    pub column: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct DashboardComponentColumn {
    #[serde(rename = "breakPoint1", default)]
    pub break_point_1: f64,
    #[serde(rename = "breakPoint2", default)]
    pub break_point_2: f64,
    #[serde(rename = "breakPointOrder", default)]
    pub break_point_order: f64,
    #[serde(rename = "highRangeColor", default)]
    pub high_range_color: f64,
    #[serde(rename = "lowRangeColor", default)]
    pub low_range_color: f64,
    #[serde(rename = "midRangeColor", default)]
    pub mid_range_color: f64,
    #[serde(rename = "reportColumn", default)]
    pub report_column: String,
    #[serde(rename = "showSubTotal", default)]
    pub show_sub_total: bool,
    #[serde(rename = "showTotal", default)]
    pub show_total: bool,
    #[serde(default)]
    pub r#type: DashboardComponentColumnType,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct ReportBucketFieldValue {
    #[serde(rename = "sourceValues", default)]
    pub source_values: Vec<ReportBucketFieldSourceValue>,
    #[serde(default)]
    pub value: String,
}
