#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: <https://github.com/forcedotcom/wsdl>
//!
//! DO NOT EDIT - This file is automatically generated

//! Search customization and configuration

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum SearchCriteriaConfigurationConfigurationType {
    #[default]
    DefaultSearch,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum SearchCriteriaConfigurationFilterType {
    #[default]
    GROUPING_AND_AGGREGATION,
    MULTIPLE_FIELDS,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum SearchCriteriaConfigurationResultDisplayFormat {
    #[default]
    LIST,
    CARD,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct SearchCriteriaConfiguration {
    #[serde(
        rename = "actionList",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub action_list: Option<String>,
    #[serde(
        rename = "additionalSearchCriteria",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub additional_search_criteria: Option<String>,
    #[serde(
        rename = "aggrCriteriaFieldset",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub aggr_criteria_fieldset: Option<serde_json::Value>,
    #[serde(
        rename = "configurationType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub configuration_type: Option<SearchCriteriaConfigurationConfigurationType>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(
        rename = "distanceCriteria",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub distance_criteria: Option<String>,
    #[serde(
        rename = "filterType",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub filter_type: Option<SearchCriteriaConfigurationFilterType>,
    #[serde(rename = "isActive", default, skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(
        rename = "isSingleFieldSort",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_single_field_sort: Option<bool>,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(
        rename = "resultDisplayFormat",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub result_display_format: Option<SearchCriteriaConfigurationResultDisplayFormat>,
    #[serde(
        rename = "resultFieldset",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub result_fieldset: Option<serde_json::Value>,
    #[serde(
        rename = "resultFlexCard",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub result_flex_card: Option<String>,
    #[serde(
        rename = "searchCriteriaFieldset",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub search_criteria_fieldset: Option<serde_json::Value>,
    #[serde(
        rename = "searchableObjDataSyncInfo",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub searchable_obj_data_sync_info: Option<String>,
    #[serde(rename = "searchableObject", default)]
    pub searchable_object: String,
    #[serde(
        rename = "sortingCriteriaFieldset",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub sorting_criteria_fieldset: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct SearchCustomization {
    #[serde(default)]
    pub channel: String,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(rename = "objectOverride", default)]
    pub object_override: Vec<SearchCustomizationObjectOverride>,
    #[serde(rename = "objectToAlwaysSearch", default)]
    pub object_to_always_search: Vec<String>,
    #[serde(rename = "selectedObject", default)]
    pub selected_object: Vec<String>,
    #[serde(rename = "selectedProfile", default)]
    pub selected_profile: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct SearchCustomizationExplicitFilter {
    #[serde(rename = "fieldPath", default, skip_serializing_if = "Option::is_none")]
    pub field_path: Option<String>,
    #[serde(rename = "type", default)]
    pub r#type: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct SearchCustomizationFieldOverride {
    #[serde(rename = "fieldApiName", default)]
    pub field_api_name: String,
    #[serde(default)]
    pub searchable: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct SearchCustomizationObjectOverride {
    #[serde(rename = "explicitFilter", default)]
    pub explicit_filter: Vec<SearchCustomizationExplicitFilter>,
    #[serde(rename = "fieldOverride", default)]
    pub field_override: Vec<SearchCustomizationFieldOverride>,
    #[serde(rename = "objectApiName", default)]
    pub object_api_name: String,
    #[serde(default)]
    pub rule: Vec<SearchCustomizationRule>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub searchable: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct SearchCustomizationRule {
    #[serde(rename = "fieldApiName", default)]
    pub field_api_name: String,
    #[serde(default)]
    pub operator: String,
    #[serde(rename = "ruleValue", default)]
    pub rule_value: Vec<SearchCustomizationRuleValue>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct SearchCustomizationRuleValue {
    #[serde(
        rename = "targetObjectApiName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub target_object_api_name: Option<String>,
    #[serde(default)]
    pub value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct SearchOrgWideFieldConfig {
    #[serde(rename = "fieldReference", default)]
    pub field_reference: String,
    #[serde(
        rename = "isSearchable",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_searchable: Option<bool>,
    #[serde(rename = "isSecure", default, skip_serializing_if = "Option::is_none")]
    pub is_secure: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct SearchOrgWideObjectConfig {
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(rename = "objectReference", default)]
    pub object_reference: String,
    #[serde(rename = "searchOrgWideFieldConfig", default)]
    pub search_org_wide_field_config: Vec<SearchOrgWideFieldConfig>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct SearchSettingsByObject {
    #[serde(rename = "searchSettingsByObject", default)]
    pub search_settings_by_object: Vec<serde_json::Value>,
}
