#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: https://github.com/forcedotcom/wsdl
//!
//! DO NOT EDIT - This file is automatically generated

//! Translations, Localization

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum TranslationAspect {
    #[default]
    Master,
    RelationshipLabel,
    Description,
    Help,
    NameFieldLabel,
    ErrorMessage,
    InfoMessage,
    PausedText,
    InputLabel,
    NextOrFinishLabel,
    BackLabel,
    PauseLabel,
    FirstName,
    LastName,
    MiddleName,
    Salutation,
    Suffix,
    InformalName,
    Title,
    Phone,
    Email,
    Address,
    Street,
    City,
    State,
    StateCode,
    PostalCode,
    Country,
    CountryCode,
    Latitude,
    Longitude,
    Body,
    Summary,
    Url,
    ActionButtonLink,
    ActionButtonLabel,
    DismissButtonLabel,
    Header,
    VideoLink,
    ImageAltText,
    ImageLink,
    Custom,
    DefaultValue,
    Version,
    AttributeName,
    UsageType,
    ProcessName,
    GroupName,
    Label,
    ParameterValue,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct StandardFieldTranslation {
    #[serde(default)]
    pub label: String,
    #[serde(default)]
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct Translations {
    #[serde(rename = "aiCoachAgentScnrDefs", default)]
    pub ai_coach_agent_scnr_defs: Vec<serde_json::Value>,
    #[serde(rename = "botBlocks", default)]
    pub bot_blocks: Vec<serde_json::Value>,
    #[serde(rename = "botTemplates", default)]
    pub bot_templates: Vec<serde_json::Value>,
    #[serde(default)]
    pub bots: Vec<serde_json::Value>,
    #[serde(rename = "conversationMessageDefinitions", default)]
    pub conversation_message_definitions: Vec<serde_json::Value>,
    #[serde(rename = "customApplications", default)]
    pub custom_applications: Vec<serde_json::Value>,
    #[serde(rename = "customLabels", default)]
    pub custom_labels: Vec<serde_json::Value>,
    #[serde(rename = "customPageWebLinks", default)]
    pub custom_page_web_links: Vec<serde_json::Value>,
    #[serde(rename = "customTabs", default)]
    pub custom_tabs: Vec<serde_json::Value>,
    #[serde(rename = "dataConnectors", default)]
    pub data_connectors: Vec<serde_json::Value>,
    #[serde(rename = "desFieldTemplateMessages", default)]
    pub des_field_template_messages: Vec<serde_json::Value>,
    #[serde(rename = "flowDefinitions", default)]
    pub flow_definitions: Vec<serde_json::Value>,
    #[serde(rename = "identityVerificationCustomFieldLabels", default)]
    pub identity_verification_custom_field_labels: Vec<serde_json::Value>,
    #[serde(rename = "pipelineInspMetricConfigs", default)]
    pub pipeline_insp_metric_configs: Vec<serde_json::Value>,
    #[serde(default)]
    pub prompts: Vec<serde_json::Value>,
    #[serde(rename = "quickActions", default)]
    pub quick_actions: Vec<serde_json::Value>,
    #[serde(rename = "reportTypes", default)]
    pub report_types: Vec<serde_json::Value>,
    #[serde(default)]
    pub scontrols: Vec<serde_json::Value>,
    #[serde(rename = "svcCatalogItemAttributes", default)]
    pub svc_catalog_item_attributes: Vec<serde_json::Value>,
    #[serde(rename = "svcCatalogItemGroups", default)]
    pub svc_catalog_item_groups: Vec<serde_json::Value>,
}

