#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: <https://github.com/forcedotcom/wsdl>
//!
//! DO NOT EDIT - This file is automatically generated

//! UI Configuration, UI Formulas, UI Formats

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum UiLoginFlowType {
    #[default]
    VisualWorkflow,
    VisualForce,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum UiType {
    #[default]
    Aloha,
    Lightning,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct UiFormatSpecification {
    #[serde(rename = "formatProperties", default)]
    pub format_properties: String,
    #[serde(rename = "formatType", default)]
    pub format_type: serde_json::Value,
    #[serde(default)]
    pub order: f64,
    #[serde(
        rename = "visibilityRule",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub visibility_rule: Option<UiFormulaRule>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct UiFormatSpecificationSet {
    #[serde(default)]
    pub field: String,
    #[serde(rename = "formatType", default)]
    pub format_type: serde_json::Value,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(rename = "sobjectType", default)]
    pub sobject_type: String,
    #[serde(rename = "uiFormatSpecifications", default)]
    pub ui_format_specifications: Vec<UiFormatSpecification>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct UiFormulaCriterion {
    #[serde(rename = "leftValue", default)]
    pub left_value: String,
    #[serde(default)]
    pub operator: String,
    #[serde(
        rename = "rightValue",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub right_value: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct UiFormulaRule {
    #[serde(
        rename = "booleanFilter",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub boolean_filter: Option<String>,
    #[serde(default)]
    pub criteria: Vec<UiFormulaCriterion>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct UiPlugin {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "extensionPointIdentifier", default)]
    pub extension_point_identifier: String,
    #[serde(rename = "isEnabled", default)]
    pub is_enabled: bool,
    #[serde(default)]
    pub language: String,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct UiPreviewMessageTabDef {
    #[serde(rename = "isActive", default)]
    pub is_active: bool,
    #[serde(
        rename = "isProtected",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub is_protected: Option<bool>,
    #[serde(default)]
    pub label: String,
    #[serde(rename = "lightningComponentDef", default)]
    pub lightning_component_def: String,
    #[serde(rename = "supportedChannel", default)]
    pub supported_channel: serde_json::Value,
    #[serde(rename = "tabName", default)]
    pub tab_name: String,
}
