#![allow(non_camel_case_types)]
//! Auto-generated Salesforce metadata types from @salesforce/types
//! Source: https://github.com/forcedotcom/wsdl
//!
//! DO NOT EDIT - This file is automatically generated

//! User Access Policies, User Provisioning, User Criteria

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum UserAccessPolicyActionTargetType {
    #[default]
    PermissionSet,
    PermissionSetGroup,
    PermissionSetLicense,
    PackageLicense,
    Group,
    Queue,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum UserAccessPolicyActionType {
    #[default]
    Grant,
    Revoke,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum UserAccessPolicyFilterOperation {
    #[default]
    equals,
    equalsIgnoreCase,
    notEquals,
    #[serde(rename = "in")]
    r#in,
    includes,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum UserAccessPolicyFilterTargetType {
    #[default]
    Group,
    Queue,
    PermissionSet,
    PermissionSetGroup,
    PermissionSetLicense,
    Profile,
    UserRole,
    PackageLicense,
    User,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum UserAccessPolicyStatus {
    #[default]
    Design,
    Testing,
    Migrate,
    Updating,
    Failed,
    Active,
    Completed,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum UserAccessPolicyTriggerType {
    #[default]
    Create,
    Update,
    CreateAndUpdate,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum UserDateGranularity {
    #[default]
    None,
    Day,
    Week,
    Month,
    Quarter,
    Year,
    FiscalQuarter,
    FiscalYear,
    MonthInYear,
    DayInMonth,
    FiscalPeriod,
    FiscalWeek,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum UserDateInterval {
    #[default]
    INTERVAL_CURRENT,
    INTERVAL_CURNEXT1,
    INTERVAL_CURPREV1,
    INTERVAL_NEXT1,
    INTERVAL_PREV1,
    INTERVAL_CURNEXT3,
    INTERVAL_CURFY,
    INTERVAL_PREVFY,
    INTERVAL_PREV2FY,
    INTERVAL_AGO2FY,
    INTERVAL_NEXTFY,
    INTERVAL_PREVCURFY,
    INTERVAL_PREVCUR2FY,
    INTERVAL_CURNEXTFY,
    INTERVAL_CUSTOM,
    INTERVAL_YESTERDAY,
    INTERVAL_TODAY,
    INTERVAL_TOMORROW,
    INTERVAL_LASTWEEK,
    INTERVAL_THISWEEK,
    INTERVAL_NEXTWEEK,
    INTERVAL_LASTMONTH,
    INTERVAL_THISMONTH,
    INTERVAL_NEXTMONTH,
    INTERVAL_LASTTHISMONTH,
    INTERVAL_THISNEXTMONTH,
    INTERVAL_CURRENTQ,
    INTERVAL_CURNEXTQ,
    INTERVAL_CURPREVQ,
    INTERVAL_NEXTQ,
    INTERVAL_PREVQ,
    INTERVAL_CURNEXT3Q,
    INTERVAL_CURY,
    INTERVAL_PREVY,
    INTERVAL_PREV2Y,
    INTERVAL_AGO2Y,
    INTERVAL_NEXTY,
    INTERVAL_PREVCURY,
    INTERVAL_PREVCUR2Y,
    INTERVAL_CURNEXTY,
    INTERVAL_LAST7,
    INTERVAL_LAST30,
    INTERVAL_LAST60,
    INTERVAL_LAST90,
    INTERVAL_LAST120,
    INTERVAL_NEXT7,
    INTERVAL_NEXT30,
    INTERVAL_NEXT60,
    INTERVAL_NEXT90,
    INTERVAL_NEXT120,
    LAST_FISCALWEEK,
    THIS_FISCALWEEK,
    NEXT_FISCALWEEK,
    LAST_FISCALPERIOD,
    THIS_FISCALPERIOD,
    NEXT_FISCALPERIOD,
    LASTTHIS_FISCALPERIOD,
    THISNEXT_FISCALPERIOD,
    CURRENT_ENTITLEMENT_PERIOD,
    PREVIOUS_ENTITLEMENT_PERIOD,
    PREVIOUS_TWO_ENTITLEMENT_PERIODS,
    TWO_ENTITLEMENT_PERIODS_AGO,
    CURRENT_AND_PREVIOUS_ENTITLEMENT_PERIOD,
    CURRENT_AND_PREVIOUS_TWO_ENTITLEMENT_PERIODS,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct UserAccessPolicy {
    #[serde(rename = "booleanFilter", default)]
    pub boolean_filter: String,
    #[serde(default)]
    pub description: String,
    #[serde(rename = "isProtected", default)]
    pub is_protected: bool,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(default)]
    pub order: f64,
    #[serde(default)]
    pub status: UserAccessPolicyStatus,
    #[serde(rename = "triggerType", default)]
    pub trigger_type: UserAccessPolicyTriggerType,
    #[serde(rename = "userAccessPolicyActions", default)]
    pub user_access_policy_actions: Vec<UserAccessPolicyAction>,
    #[serde(rename = "userAccessPolicyFilters", default)]
    pub user_access_policy_filters: Vec<UserAccessPolicyFilter>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct UserAccessPolicyAction {
    #[serde(default)]
    pub action: UserAccessPolicyActionType,
    #[serde(default)]
    pub target: String,
    #[serde(default)]
    pub r#type: UserAccessPolicyActionTargetType,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct UserAccessPolicyFilter {
    #[serde(rename = "columnName", default)]
    pub column_name: String,
    #[serde(default)]
    pub operation: UserAccessPolicyFilterOperation,
    #[serde(rename = "sortOrder", default)]
    pub sort_order: f64,
    #[serde(default)]
    pub target: String,
    #[serde(default)]
    pub r#type: UserAccessPolicyFilterTargetType,
    #[serde(default)]
    pub value: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct UserCriteria {
    #[serde(rename = "creationAgeInSeconds", default)]
    pub creation_age_in_seconds: f64,
    #[serde(default)]
    pub description: String,
    #[serde(rename = "lastChatterActivityAgeInSeconds", default)]
    pub last_chatter_activity_age_in_seconds: f64,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(default)]
    pub profiles: Vec<String>,
    #[serde(rename = "userTypes", default)]
    pub user_types: Vec<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct UserLicenseDefinition {
    #[serde(rename = "cloudServiceProvider", default)]
    pub cloud_service_provider: String,
    #[serde(rename = "defaultLicenseDuration", default)]
    pub default_license_duration: f64,
    #[serde(rename = "defaultStatus", default)]
    pub default_status: serde_json::Value,
    #[serde(default)]
    pub description: String,
    #[serde(rename = "hasDynamicResourceGroupKey", default)]
    pub has_dynamic_resource_group_key: bool,
    #[serde(rename = "includedFeatures", default)]
    pub included_features: Vec<serde_json::Value>,
    #[serde(rename = "isPermissionSetLicense", default)]
    pub is_permission_set_license: bool,
    #[serde(rename = "licenseKey", default)]
    pub license_key: String,
    #[serde(rename = "licenseOwner", default)]
    pub license_owner: String,
    #[serde(rename = "licensingAuthority", default)]
    pub licensing_authority: String,
    #[serde(rename = "managementServiceProvider", default)]
    pub management_service_provider: String,
    #[serde(rename = "managementTenantId", default)]
    pub management_tenant_id: String,
    #[serde(rename = "minPlatformVersion", default)]
    pub min_platform_version: f64,
    #[serde(default)]
    pub name: String,
    #[serde(rename = "recordVisibility", default)]
    pub record_visibility: String,
    #[serde(rename = "settingItems", default)]
    pub setting_items: Vec<serde_json::Value>,
    #[serde(rename = "settingUsageDefinitions", default)]
    pub setting_usage_definitions: Vec<serde_json::Value>,
    #[serde(rename = "standardPermissionSets", default)]
    pub standard_permission_sets: Vec<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct UserProvisioningConfig {
    #[serde(rename = "approvalRequired", default)]
    pub approval_required: String,
    #[serde(rename = "connectedApp", default)]
    pub connected_app: String,
    #[serde(default)]
    pub enabled: bool,
    #[serde(rename = "enabledOperations", default)]
    pub enabled_operations: String,
    #[serde(default)]
    pub flow: String,
    #[serde(rename = "masterLabel", default)]
    pub master_label: String,
    #[serde(rename = "namedCredential", default)]
    pub named_credential: String,
    #[serde(default)]
    pub notes: String,
    #[serde(rename = "onUpdateAttributes", default)]
    pub on_update_attributes: String,
    #[serde(rename = "reconFilter", default)]
    pub recon_filter: String,
    #[serde(rename = "userAccountMapping", default)]
    pub user_account_mapping: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
pub struct Users {
    #[serde(default)]
    pub user: Vec<String>,
}
